import React from 'react';
import {
	IonItem,
	IonLabel,
	IonSelect,
	IonSelectOption,
	IonContent,
	IonHeader,
	IonToolbar,
	IonPage,
	IonTitle,
	IonList,
	} from '@ionic/react';

const Tab3Page: React.FC = () => {
	return (
		<IonPage>
			<IonHeader>
				<IonToolbar>
					<IonTitle>Settings</IonTitle>
				</IonToolbar>
			</IonHeader>
			<IonContent>
				<IonItem>
					<IonLabel>City</IonLabel>
					<IonSelect placeholder="Select One">
						<IonList>
							<IonSelectOption value="m">No Selection</IonSelectOption>
							<IonSelectOption value="a">Ada</IonSelectOption>
							<IonSelectOption value="s">Adams</IonSelectOption>
							<IonSelectOption value="d">Adrian</IonSelectOption>
							<IonSelectOption value="f">Afton</IonSelectOption>
							<IonSelectOption value="g">Aitkin</IonSelectOption>
							<IonSelectOption value="h">Akeley</IonSelectOption>
							<IonSelectOption value="j">Albany</IonSelectOption>
							<IonSelectOption value="k">Albert Lea</IonSelectOption>
							<IonSelectOption value="l">Alberta</IonSelectOption>
							<IonSelectOption value=";">Albertville</IonSelectOption>
							<IonSelectOption value="ma">Alden</IonSelectOption>
							<IonSelectOption value="ms">Aldrich</IonSelectOption>
							<IonSelectOption value="md">Alexandria</IonSelectOption>
							<IonSelectOption value="mf">Alpha</IonSelectOption>
							<IonSelectOption value="mg">Altura</IonSelectOption>
							<IonSelectOption value="mh">Alvarado</IonSelectOption>
							<IonSelectOption value="mj">Amboy</IonSelectOption>
							<IonSelectOption value="mk">Andover</IonSelectOption>
							<IonSelectOption value="ml">Annandale</IonSelectOption>
							<IonSelectOption value="m;">Anoka</IonSelectOption>
							<IonSelectOption value="1m">Apple Valley</IonSelectOption>
							<IonSelectOption value="m1">Appleton</IonSelectOption>
							<IonSelectOption value="m2">Arco</IonSelectOption>
							<IonSelectOption value="m3">Arden Hills</IonSelectOption>
							<IonSelectOption value="m4">Argyle</IonSelectOption>
							<IonSelectOption value="m5">Arlington</IonSelectOption>
							<IonSelectOption value="m6">Ashby</IonSelectOption>
							<IonSelectOption value="m7">Askov</IonSelectOption>
							<IonSelectOption value="m8">Atwater</IonSelectOption>
							<IonSelectOption value="m9">Audubon</IonSelectOption>
							<IonSelectOption value="m0">Aurora</IonSelectOption>
							<IonSelectOption value="m-">Austin</IonSelectOption>
							<IonSelectOption value="m=">Avoca</IonSelectOption>
							<IonSelectOption value="mz">Avon</IonSelectOption>
							<IonSelectOption value="mx">Bloomington</IonSelectOption>
							<IonSelectOption value="mc">Babbitt</IonSelectOption>
							<IonSelectOption value="mv">Backus</IonSelectOption>
							<IonSelectOption value="mb">Badger</IonSelectOption>
							<IonSelectOption value="mn">Bagley</IonSelectOption>
							<IonSelectOption value="mm">Balaton</IonSelectOption>
							<IonSelectOption value="m,">Barnesville</IonSelectOption>
							<IonSelectOption value="m.">Barnum</IonSelectOption>
							<IonSelectOption value="m/">Barrett</IonSelectOption>
							<IonSelectOption value="am">Barry</IonSelectOption>
							<IonSelectOption value="sm">Battle Lake</IonSelectOption>
							<IonSelectOption value="dm">Baudette</IonSelectOption>
							<IonSelectOption value="fm">Baxter</IonSelectOption>
							<IonSelectOption value="gm">Bayport</IonSelectOption>
							<IonSelectOption value="hm">Beardsley</IonSelectOption>
							<IonSelectOption value="jm">Beaver Bay</IonSelectOption>
							<IonSelectOption value="km">Beaver Creek</IonSelectOption>
							<IonSelectOption value="lm">Becker</IonSelectOption>
							<IonSelectOption value=";m">Bejou</IonSelectOption>
							<IonSelectOption value="qm">Belgrade</IonSelectOption>
							<IonSelectOption value="wm">Belle Plaine</IonSelectOption>
							<IonSelectOption value="em">Bellechester</IonSelectOption>
							<IonSelectOption value="rm">Bellingham</IonSelectOption>
							<IonSelectOption value="tm">Beltrami</IonSelectOption>
							<IonSelectOption value="ym">Belview</IonSelectOption>
							<IonSelectOption value="um">Bemidji</IonSelectOption>
							<IonSelectOption value="im">Bena</IonSelectOption>
							<IonSelectOption value="om">Benson</IonSelectOption>
							<IonSelectOption value="pm">Beroun</IonSelectOption>
							<IonSelectOption value="[m">Bertha</IonSelectOption>
							<IonSelectOption value="]m">Bethel</IonSelectOption>
							<IonSelectOption value="qm">Big Falls</IonSelectOption>
							<IonSelectOption value="qqm">Big Lake</IonSelectOption>
							<IonSelectOption value="mww">Bigelow</IonSelectOption>
							<IonSelectOption value="mqw">Bigfork</IonSelectOption>
							<IonSelectOption value="mqwer">Bingham Lake</IonSelectOption>
							<IonSelectOption value="mwer">Birchwood Village</IonSelectOption>
							<IonSelectOption value="qwem">Bird Island</IonSelectOption>
							<IonSelectOption value="mew">Biscay</IonSelectOption>
							<IonSelectOption value="mdfa">Biwabik</IonSelectOption>
							<IonSelectOption value="zxvm">Blackduck</IonSelectOption>
							<IonSelectOption value="ms">Blaine</IonSelectOption>
							<IonSelectOption value="mvd">Blomkest</IonSelectOption>
							<IonSelectOption value="msda">Blooming Prairie</IonSelectOption>
							<IonSelectOption value="mgf">Bloomington</IonSelectOption>
							<IonSelectOption value="mgfh">Blue Earth</IonSelectOption>
							<IonSelectOption value="mfdc">Bluffton</IonSelectOption>
							<IonSelectOption value="mfx">Bock</IonSelectOption>
							<IonSelectOption value="m">Borup</IonSelectOption>
							<IonSelectOption value="m">Bovey</IonSelectOption>
							<IonSelectOption value="m">Bowlus</IonSelectOption>
							<IonSelectOption value="m">Boy River</IonSelectOption>
							<IonSelectOption value="m">Boyd</IonSelectOption>
							<IonSelectOption value="m">Braham</IonSelectOption>
							<IonSelectOption value="m">Brainerd</IonSelectOption>
							<IonSelectOption value="m">Brandon</IonSelectOption>
							<IonSelectOption value="m">Breckenridge</IonSelectOption>
							<IonSelectOption value="m">Breezy Point</IonSelectOption>
							<IonSelectOption value="m">Brewster</IonSelectOption>
							<IonSelectOption value="m">Bricelyn</IonSelectOption>
							<IonSelectOption value="m">Brook Park</IonSelectOption>
							<IonSelectOption value="m">Brooklyn Center</IonSelectOption>
							<IonSelectOption value="m">Brooklyn Park</IonSelectOption>
							<IonSelectOption value="m">Brooks</IonSelectOption>
							<IonSelectOption value="m">Brookston</IonSelectOption>
							<IonSelectOption value="m">Brooten</IonSelectOption>
							<IonSelectOption value="m">Browerville</IonSelectOption>
							<IonSelectOption value="m">Browns Valley</IonSelectOption>
							<IonSelectOption value="m">Brownsdale</IonSelectOption>
							<IonSelectOption value="m">Brownsville</IonSelectOption>
							<IonSelectOption value="m">Brownton</IonSelectOption>
							<IonSelectOption value="m">Bruno</IonSelectOption>
							<IonSelectOption value="m">Buckman</IonSelectOption>
							<IonSelectOption value="m">Buffalo</IonSelectOption>
							<IonSelectOption value="m">Buffalo Lake</IonSelectOption>
							<IonSelectOption value="m">Buhl</IonSelectOption>
							<IonSelectOption value="m">Burnsville</IonSelectOption>
							<IonSelectOption value="m">Burtrum</IonSelectOption>
							<IonSelectOption value="m">Butterfield</IonSelectOption>
							<IonSelectOption value="m">Byron</IonSelectOption>
							<IonSelectOption value="m">Caledonia</IonSelectOption>
							<IonSelectOption value="m">Callaway</IonSelectOption>
							<IonSelectOption value="m">Calumet</IonSelectOption>
							<IonSelectOption value="m">Cambridge</IonSelectOption>
							<IonSelectOption value="m">Campbell</IonSelectOption>
							<IonSelectOption value="m">Canby</IonSelectOption>
							<IonSelectOption value="m">Cannon Falls</IonSelectOption>
							<IonSelectOption value="m">Canton</IonSelectOption>
							<IonSelectOption value="m">Carlos</IonSelectOption>
							<IonSelectOption value="m">Carlton</IonSelectOption>
							<IonSelectOption value="m">Carver</IonSelectOption>
							<IonSelectOption value="m">Cass Lake</IonSelectOption>
							<IonSelectOption value="m">Cedar Mills</IonSelectOption>
							<IonSelectOption value="m">Center City</IonSelectOption>
							<IonSelectOption value="m">Centerville</IonSelectOption>
							<IonSelectOption value="m">Ceylon</IonSelectOption>
							<IonSelectOption value="m">Champlin</IonSelectOption>
							<IonSelectOption value="m">Chandler</IonSelectOption>
							<IonSelectOption value="m">Chanhassen</IonSelectOption>
							<IonSelectOption value="m">Chaska</IonSelectOption>
							<IonSelectOption value="m">Chatfield</IonSelectOption>
							<IonSelectOption value="m">Chickamaw Beach</IonSelectOption>
							<IonSelectOption value="m">Chisago City</IonSelectOption>
							<IonSelectOption value="m">Chisholm</IonSelectOption>
							<IonSelectOption value="m">Chokio</IonSelectOption>
							<IonSelectOption value="m">Circle Pines</IonSelectOption>
							<IonSelectOption value="m">Clara City</IonSelectOption>
							<IonSelectOption value="m">Claremont</IonSelectOption>
							<IonSelectOption value="m">Clarissa</IonSelectOption>
							<IonSelectOption value="m">Clarkfield</IonSelectOption>
							<IonSelectOption value="m">Clarks Grove</IonSelectOption>
							<IonSelectOption value="m">Clear Lake</IonSelectOption>
							<IonSelectOption value="m">Clearbrook</IonSelectOption>
							<IonSelectOption value="m">Clearwater</IonSelectOption>
							<IonSelectOption value="m">Clements</IonSelectOption>
							<IonSelectOption value="m">Cleveland</IonSelectOption>
							<IonSelectOption value="m">Climax</IonSelectOption>
							<IonSelectOption value="m">Clinton</IonSelectOption>
							<IonSelectOption value="m">Clitherall</IonSelectOption>
							<IonSelectOption value="m">Clontarf</IonSelectOption>
							<IonSelectOption value="m">Cloquet</IonSelectOption>
							<IonSelectOption value="m">Coates</IonSelectOption>
							<IonSelectOption value="m">Cobden</IonSelectOption>
							<IonSelectOption value="m">Cohasset</IonSelectOption>
							<IonSelectOption value="m">Cokato</IonSelectOption>
							<IonSelectOption value="m">Cold Spring</IonSelectOption>
							<IonSelectOption value="m">Coleraine</IonSelectOption>
							<IonSelectOption value="m">Collegeville</IonSelectOption>
							<IonSelectOption value="m">Cologne</IonSelectOption>
							<IonSelectOption value="m">Columbia Heights</IonSelectOption>
							<IonSelectOption value="m">Columbus</IonSelectOption>
							<IonSelectOption value="m">Comfrey</IonSelectOption>
							<IonSelectOption value="m">Comstock</IonSelectOption>
							<IonSelectOption value="m">Conger</IonSelectOption>
							<IonSelectOption value="m">Cook</IonSelectOption>
							<IonSelectOption value="m">Coon Rapids</IonSelectOption>
							<IonSelectOption value="m">Corcoran</IonSelectOption>
							<IonSelectOption value="m">Correll</IonSelectOption>
							<IonSelectOption value="m">Cosmos</IonSelectOption>
							<IonSelectOption value="m">Cottage Grove</IonSelectOption>
							<IonSelectOption value="m">Cottonwood</IonSelectOption>
							<IonSelectOption value="m">Courtland</IonSelectOption>
							<IonSelectOption value="m">Cromwell</IonSelectOption>
							<IonSelectOption value="m">Crookston</IonSelectOption>
							<IonSelectOption value="m">Crosby</IonSelectOption>
							<IonSelectOption value="m">Crosslake</IonSelectOption>
							<IonSelectOption value="m">Crystal</IonSelectOption>
							<IonSelectOption value="m">Currie</IonSelectOption>
							<IonSelectOption value="m">Cuyuna</IonSelectOption>
							<IonSelectOption value="m">Cyrus</IonSelectOption>
							<IonSelectOption value="m">Duluth</IonSelectOption>
							<IonSelectOption value="m">Dakota</IonSelectOption>
							<IonSelectOption value="m">Dalton</IonSelectOption>
							<IonSelectOption value="m">Danube</IonSelectOption>
							<IonSelectOption value="m">Danvers</IonSelectOption>
							<IonSelectOption value="m">Darfur</IonSelectOption>
							<IonSelectOption value="m">Darwin</IonSelectOption>
							<IonSelectOption value="m">Dassel</IonSelectOption>
							<IonSelectOption value="m">Dawson</IonSelectOption>
							<IonSelectOption value="m">Dayton</IonSelectOption>
							<IonSelectOption value="m">De Graff</IonSelectOption>
							<IonSelectOption value="m">Deephaven</IonSelectOption>
							<IonSelectOption value="m">Deer Creek</IonSelectOption>
							<IonSelectOption value="m">Deer River</IonSelectOption>
							<IonSelectOption value="m">Deerwood</IonSelectOption>
							<IonSelectOption value="m">Delano</IonSelectOption>
							<IonSelectOption value="m">Delavan</IonSelectOption>
							<IonSelectOption value="m">Delft</IonSelectOption>
							<IonSelectOption value="m">Delhi</IonSelectOption>
							<IonSelectOption value="m">Dellwood</IonSelectOption>
							<IonSelectOption value="m">Denham</IonSelectOption>
							<IonSelectOption value="m">Dennison</IonSelectOption>
							<IonSelectOption value="m">Dent</IonSelectOption>
							<IonSelectOption value="m">Detroit Lakes</IonSelectOption>
							<IonSelectOption value="m">Dexter</IonSelectOption>
							<IonSelectOption value="m">Dilworth</IonSelectOption>
							<IonSelectOption value="m">Dodge Center</IonSelectOption>
							<IonSelectOption value="m">Donaldson</IonSelectOption>
							<IonSelectOption value="m">Donnelly</IonSelectOption>
							<IonSelectOption value="m">Doran</IonSelectOption>
							<IonSelectOption value="m">Dover</IonSelectOption>
							<IonSelectOption value="m">Dovray</IonSelectOption>
							<IonSelectOption value="m">Duluth</IonSelectOption>
							<IonSelectOption value="m">Dumont</IonSelectOption>
							<IonSelectOption value="m">Dundas</IonSelectOption>
							<IonSelectOption value="m">Dundee</IonSelectOption>
							<IonSelectOption value="m">Eagan</IonSelectOption>
							<IonSelectOption value="m">Eagle Bend</IonSelectOption>
							<IonSelectOption value="m">Eagle Lake</IonSelectOption>
							<IonSelectOption value="m">East Bethel</IonSelectOption>
							<IonSelectOption value="m">East Grand Forks</IonSelectOption>
							<IonSelectOption value="m">East Gull Lake</IonSelectOption>
							<IonSelectOption value="m">Easton</IonSelectOption>
							<IonSelectOption value="m">Echo</IonSelectOption>
							<IonSelectOption value="m">Eden Prairie</IonSelectOption>
							<IonSelectOption value="m">Eden Valley</IonSelectOption>
							<IonSelectOption value="m">Edgerton</IonSelectOption>
							<IonSelectOption value="m">Edina</IonSelectOption>
							<IonSelectOption value="m">Effie</IonSelectOption>
							<IonSelectOption value="m">Eitzen</IonSelectOption>
							<IonSelectOption value="m">Elba</IonSelectOption>
							<IonSelectOption value="m">Elbow Lake</IonSelectOption>
							<IonSelectOption value="m">Elgin</IonSelectOption>
							<IonSelectOption value="m">Elizabeth</IonSelectOption>
							<IonSelectOption value="m">Elk River</IonSelectOption>
							<IonSelectOption value="m">Elko</IonSelectOption>
							<IonSelectOption value="m">Elkton</IonSelectOption>
							<IonSelectOption value="m">Ellendale</IonSelectOption>
							<IonSelectOption value="m">Ellsworth</IonSelectOption>
							<IonSelectOption value="m">Elmdale</IonSelectOption>
							<IonSelectOption value="m">Elmore</IonSelectOption>
							<IonSelectOption value="m">Elrosa</IonSelectOption>
							<IonSelectOption value="m">Ely</IonSelectOption>
							<IonSelectOption value="m">Elysian</IonSelectOption>
							<IonSelectOption value="m">Emily</IonSelectOption>
							<IonSelectOption value="m">Emmons</IonSelectOption>
							<IonSelectOption value="m">Erhard</IonSelectOption>
							<IonSelectOption value="m">Erskine</IonSelectOption>
							<IonSelectOption value="m">Evan</IonSelectOption>
							<IonSelectOption value="m">Evansville</IonSelectOption>
							<IonSelectOption value="m">Eveleth</IonSelectOption>
							<IonSelectOption value="m">Excelsior</IonSelectOption>
							<IonSelectOption value="m">Eyota</IonSelectOption>
							<IonSelectOption value="m">Fairfax</IonSelectOption>
							<IonSelectOption value="m">Fairmont</IonSelectOption>
							<IonSelectOption value="m">Falcon Heights</IonSelectOption>
							<IonSelectOption value="m">Faribault</IonSelectOption>
							<IonSelectOption value="m">Farming</IonSelectOption>
							<IonSelectOption value="m">Farmington</IonSelectOption>
							<IonSelectOption value="m">Farwell</IonSelectOption>
							<IonSelectOption value="m">Federal Dam</IonSelectOption>
							<IonSelectOption value="m">Felton</IonSelectOption>
							<IonSelectOption value="m">Fergus Falls</IonSelectOption>
							<IonSelectOption value="m">Fertile</IonSelectOption>
							<IonSelectOption value="m">Fifty Lakes</IonSelectOption>
							<IonSelectOption value="m">Finlayson</IonSelectOption>
							<IonSelectOption value="m">Fisher</IonSelectOption>
							<IonSelectOption value="m">Flensburg</IonSelectOption>
							<IonSelectOption value="m">Floodwood</IonSelectOption>
							<IonSelectOption value="m">Florence</IonSelectOption>
							<IonSelectOption value="m">Foley</IonSelectOption>
							<IonSelectOption value="m">Forada</IonSelectOption>
							<IonSelectOption value="m">Forest Lake</IonSelectOption>
							<IonSelectOption value="m">Foreston</IonSelectOption>
							<IonSelectOption value="m">Fort Ripley</IonSelectOption>
							<IonSelectOption value="m">Fosston</IonSelectOption>
							<IonSelectOption value="m">Fountain</IonSelectOption>
							<IonSelectOption value="m">Foxhome</IonSelectOption>
							<IonSelectOption value="m">Franklin</IonSelectOption>
							<IonSelectOption value="m">Frazee</IonSelectOption>
							<IonSelectOption value="m">Freeborn</IonSelectOption>
							<IonSelectOption value="m">Freeport</IonSelectOption>
							<IonSelectOption value="m">Fridley</IonSelectOption>
							<IonSelectOption value="m">Frost</IonSelectOption>
							<IonSelectOption value="m">Fulda</IonSelectOption>
							<IonSelectOption value="m">Funkley</IonSelectOption>
							<IonSelectOption value="m">Garfield</IonSelectOption>
							<IonSelectOption value="m">Garrison</IonSelectOption>
							<IonSelectOption value="m">Garvin</IonSelectOption>
							<IonSelectOption value="m">Gary</IonSelectOption>
							<IonSelectOption value="m">Gaylord</IonSelectOption>
							<IonSelectOption value="m">Gem Lake</IonSelectOption>
							<IonSelectOption value="m">Geneva</IonSelectOption>
							<IonSelectOption value="m">Genola</IonSelectOption>
							<IonSelectOption value="m">Georgetown</IonSelectOption>
							<IonSelectOption value="m">Ghent</IonSelectOption>
							<IonSelectOption value="m">Gibbon</IonSelectOption>
							<IonSelectOption value="m">Gilbert</IonSelectOption>
							<IonSelectOption value="m">Gilman</IonSelectOption>
							<IonSelectOption value="m">Glencoe</IonSelectOption>
							<IonSelectOption value="m">Glenville</IonSelectOption>
							<IonSelectOption value="m">Glenwood</IonSelectOption>
							<IonSelectOption value="m">Glyndon</IonSelectOption>
							<IonSelectOption value="m">Golden Valley</IonSelectOption>
							<IonSelectOption value="m">Gonvick</IonSelectOption>
							<IonSelectOption value="m">Good Thunder</IonSelectOption>
							<IonSelectOption value="m">Goodhue</IonSelectOption>
							<IonSelectOption value="m">Goodridge</IonSelectOption>
							<IonSelectOption value="m">Goodview</IonSelectOption>
							<IonSelectOption value="m">Graceville</IonSelectOption>
							<IonSelectOption value="m">Granada</IonSelectOption>
							<IonSelectOption value="m">Grand Marais</IonSelectOption>
							<IonSelectOption value="m">Grand Meadow</IonSelectOption>
							<IonSelectOption value="m">Grand Rapids</IonSelectOption>
							<IonSelectOption value="m">Granite Falls</IonSelectOption>
							<IonSelectOption value="m">Grant</IonSelectOption>
							<IonSelectOption value="m">Grasston</IonSelectOption>
							<IonSelectOption value="m">Green Isle</IonSelectOption>
							<IonSelectOption value="m">Greenbush</IonSelectOption>
							<IonSelectOption value="m">Greenfield</IonSelectOption>
							<IonSelectOption value="m">Greenwald</IonSelectOption>
							<IonSelectOption value="m">Greenwood</IonSelectOption>
							<IonSelectOption value="m">Grey Eagle</IonSelectOption>
							<IonSelectOption value="m">Grove City</IonSelectOption>
							<IonSelectOption value="m">Grygla</IonSelectOption>
							<IonSelectOption value="m">Gully</IonSelectOption>
							<IonSelectOption value="m">Hackensack</IonSelectOption>
							<IonSelectOption value="m">Hadley</IonSelectOption>
							<IonSelectOption value="m">Hallock</IonSelectOption>
							<IonSelectOption value="m">Halma</IonSelectOption>
							<IonSelectOption value="m">Halstad</IonSelectOption>
							<IonSelectOption value="m">Ham Lake</IonSelectOption>
							<IonSelectOption value="m">Hamburg</IonSelectOption>
							<IonSelectOption value="m">Hammond</IonSelectOption>
							<IonSelectOption value="m">Hampton</IonSelectOption>
							<IonSelectOption value="m">Hancock</IonSelectOption>
							<IonSelectOption value="m">Hanley Falls</IonSelectOption>
							<IonSelectOption value="m">Hanover</IonSelectOption>
							<IonSelectOption value="m">Hanska</IonSelectOption>
							<IonSelectOption value="m">Harding</IonSelectOption>
							<IonSelectOption value="m">Hardwick</IonSelectOption>
							<IonSelectOption value="m">Harmony</IonSelectOption>
							<IonSelectOption value="m">Harris</IonSelectOption>
							<IonSelectOption value="m">Hartland</IonSelectOption>
							<IonSelectOption value="m">Hastings</IonSelectOption>
							<IonSelectOption value="m">Hatfield</IonSelectOption>
							<IonSelectOption value="m">Hawley</IonSelectOption>
							<IonSelectOption value="m">Hayfield</IonSelectOption>
							<IonSelectOption value="m">Hayward</IonSelectOption>
							<IonSelectOption value="m">Hazel Run</IonSelectOption>
							<IonSelectOption value="m">Hector</IonSelectOption>
							<IonSelectOption value="m">Heidelberg</IonSelectOption>
							<IonSelectOption value="m">Henderson</IonSelectOption>
							<IonSelectOption value="m">Hendricks</IonSelectOption>
							<IonSelectOption value="m">Hendrum</IonSelectOption>
							<IonSelectOption value="m">Henning</IonSelectOption>
							<IonSelectOption value="m">Henriette</IonSelectOption>
							<IonSelectOption value="m">Herman</IonSelectOption>
							<IonSelectOption value="m">Hermantown</IonSelectOption>
							<IonSelectOption value="m">Heron Lake</IonSelectOption>
							<IonSelectOption value="m">Hewitt</IonSelectOption>
							<IonSelectOption value="m">Hibbing</IonSelectOption>
							<IonSelectOption value="m">Hill City</IonSelectOption>
							<IonSelectOption value="m">Hillman</IonSelectOption>
							<IonSelectOption value="m">Hills</IonSelectOption>
							<IonSelectOption value="m">Hilltop</IonSelectOption>
							<IonSelectOption value="m">Hinckley</IonSelectOption>
							<IonSelectOption value="m">Hitterdal</IonSelectOption>
							<IonSelectOption value="m">Hoffman</IonSelectOption>
							<IonSelectOption value="m">Hokah</IonSelectOption>
							<IonSelectOption value="m">Holdingford</IonSelectOption>
							<IonSelectOption value="m">Holland</IonSelectOption>
							<IonSelectOption value="m">Hollandale</IonSelectOption>
							<IonSelectOption value="m">Holloway</IonSelectOption>
							<IonSelectOption value="m">Holt</IonSelectOption>
							<IonSelectOption value="m">Hopkins</IonSelectOption>
							<IonSelectOption value="m">Houston</IonSelectOption>
							<IonSelectOption value="m">Howard Lake</IonSelectOption>
							<IonSelectOption value="m">Hoyt Lakes</IonSelectOption>
							<IonSelectOption value="m">Hugo</IonSelectOption>
							<IonSelectOption value="m">Humboldt</IonSelectOption>
							<IonSelectOption value="m">Hutchinson</IonSelectOption>
							<IonSelectOption value="m">Ihlen</IonSelectOption>
							<IonSelectOption value="m">Independence</IonSelectOption>
							<IonSelectOption value="m">International Falls</IonSelectOption>
							<IonSelectOption value="m">Inver Grove Heights</IonSelectOption>
							<IonSelectOption value="m">Iona</IonSelectOption>
							<IonSelectOption value="m">Iron Junction</IonSelectOption>
							<IonSelectOption value="m">Ironton</IonSelectOption>
							<IonSelectOption value="m">Isanti</IonSelectOption>
							<IonSelectOption value="m">Isle</IonSelectOption>
							<IonSelectOption value="m">Ivanhoe</IonSelectOption>
							<IonSelectOption value="m">Jackson</IonSelectOption>
							<IonSelectOption value="m">Janesville</IonSelectOption>
							<IonSelectOption value="m">Jasper</IonSelectOption>
							<IonSelectOption value="m">Jeffers</IonSelectOption>
							<IonSelectOption value="m">Jenkins</IonSelectOption>
							<IonSelectOption value="m">Johnson</IonSelectOption>
							<IonSelectOption value="m">Jordan</IonSelectOption>
							<IonSelectOption value="m">Kandiyohi</IonSelectOption>
							<IonSelectOption value="m">Karlstad</IonSelectOption>
							<IonSelectOption value="m">Kasota</IonSelectOption>
							<IonSelectOption value="m">Kasson</IonSelectOption>
							<IonSelectOption value="m">Keewatin</IonSelectOption>
							<IonSelectOption value="m">Kelliher</IonSelectOption>
							<IonSelectOption value="m">Kellogg</IonSelectOption>
							<IonSelectOption value="m">Kennedy</IonSelectOption>
							<IonSelectOption value="m">Kenneth</IonSelectOption>
							<IonSelectOption value="m">Kensington</IonSelectOption>
							<IonSelectOption value="m">Kent</IonSelectOption>
							<IonSelectOption value="m">Kenyon</IonSelectOption>
							<IonSelectOption value="m">Kerkhoven</IonSelectOption>
							<IonSelectOption value="m">Kerrick</IonSelectOption>
							<IonSelectOption value="m">Kettle River</IonSelectOption>
							<IonSelectOption value="m">Kiester</IonSelectOption>
							<IonSelectOption value="m">Kilkenny</IonSelectOption>
							<IonSelectOption value="m">Kimball</IonSelectOption>
							<IonSelectOption value="m">Kinbrae</IonSelectOption>
							<IonSelectOption value="m">Kingston</IonSelectOption>
							<IonSelectOption value="m">Kinney</IonSelectOption>
							<IonSelectOption value="m">La Crescent</IonSelectOption>
							<IonSelectOption value="m">Lafayette</IonSelectOption>
							<IonSelectOption value="m">Lake Benton</IonSelectOption>
							<IonSelectOption value="m">Lake Bronson</IonSelectOption>
							<IonSelectOption value="m">Lake City</IonSelectOption>
							<IonSelectOption value="m">Lake Crystal</IonSelectOption>
							<IonSelectOption value="m">Lake Elmo</IonSelectOption>
							<IonSelectOption value="m">Lakefield</IonSelectOption>
							<IonSelectOption value="m">Lake Henry</IonSelectOption>
							<IonSelectOption value="m">Lake Lillian</IonSelectOption>
							<IonSelectOption value="m">Lake Park</IonSelectOption>
							<IonSelectOption value="m">Lake St. Croix Beach</IonSelectOption>
							<IonSelectOption value="m">Lake Shore</IonSelectOption>
							<IonSelectOption value="m">Lake Wilson</IonSelectOption>
							<IonSelectOption value="m">Lakeland</IonSelectOption>
							<IonSelectOption value="m">Lakeland Shores</IonSelectOption>
							<IonSelectOption value="m">Lakeville</IonSelectOption>
							<IonSelectOption value="m">Lamberton</IonSelectOption>
							<IonSelectOption value="m">Lancaster</IonSelectOption>
							<IonSelectOption value="m">Landfall</IonSelectOption>
							<IonSelectOption value="m">Lanesboro</IonSelectOption>
							<IonSelectOption value="m">La Prairie</IonSelectOption>
							<IonSelectOption value="m">La Salle</IonSelectOption>
							<IonSelectOption value="m">Laporte</IonSelectOption>
							<IonSelectOption value="m">Lastrup</IonSelectOption>
							<IonSelectOption value="m">Lauderdale</IonSelectOption>
							<IonSelectOption value="m">Le Center</IonSelectOption>
							<IonSelectOption value="m">Le Roy</IonSelectOption>
							<IonSelectOption value="m">Le Sueur</IonSelectOption>
							<IonSelectOption value="m">Lengby</IonSelectOption>
							<IonSelectOption value="m">Leonard</IonSelectOption>
							<IonSelectOption value="m">Leonidas</IonSelectOption>
							<IonSelectOption value="m">Lester Prairie</IonSelectOption>
							<IonSelectOption value="m">Lewiston</IonSelectOption>
							<IonSelectOption value="m">Lewisville</IonSelectOption>
							<IonSelectOption value="m">Lexington</IonSelectOption>
							<IonSelectOption value="m">Lilydale</IonSelectOption>
							<IonSelectOption value="m">Lindstrom</IonSelectOption>
							<IonSelectOption value="m">Lino Lakes</IonSelectOption>
							<IonSelectOption value="m">Lismore</IonSelectOption>
							<IonSelectOption value="m">Litchfield</IonSelectOption>
							<IonSelectOption value="m">Little Canada</IonSelectOption>
							<IonSelectOption value="m">Little Falls</IonSelectOption>
							<IonSelectOption value="m">Littlefork</IonSelectOption>
							<IonSelectOption value="m">Long Beach</IonSelectOption>
							<IonSelectOption value="m">Long Lake</IonSelectOption>
							<IonSelectOption value="m">Long Prairie</IonSelectOption>
							<IonSelectOption value="m">Longville</IonSelectOption>
							<IonSelectOption value="m">Lonsdale</IonSelectOption>
							<IonSelectOption value="m">Loretto</IonSelectOption>
							<IonSelectOption value="m">Louisburg</IonSelectOption>
							<IonSelectOption value="m">Lowry</IonSelectOption>
							<IonSelectOption value="m">Lucan</IonSelectOption>
							<IonSelectOption value="m">Luverne</IonSelectOption>
							<IonSelectOption value="m">Lyle</IonSelectOption>
							<IonSelectOption value="m">Lynd</IonSelectOption>
							<IonSelectOption value="m">Mabel</IonSelectOption>
							<IonSelectOption value="m">McGrath</IonSelectOption>
							<IonSelectOption value="m">McGregor</IonSelectOption>
							<IonSelectOption value="m">McIntosh</IonSelectOption>
							<IonSelectOption value="m">McKinley</IonSelectOption>
							<IonSelectOption value="m">Madelia</IonSelectOption>
							<IonSelectOption value="m">Madison</IonSelectOption>
							<IonSelectOption value="m">Madison Lake</IonSelectOption>
							<IonSelectOption value="m">Magnolia</IonSelectOption>
							<IonSelectOption value="m">Mahnomen</IonSelectOption>
							<IonSelectOption value="m">Mahtomedi</IonSelectOption>
							<IonSelectOption value="m">Manchester</IonSelectOption>
							<IonSelectOption value="m">Manhattan Beach</IonSelectOption>
							<IonSelectOption value="m">Mankato</IonSelectOption>
							<IonSelectOption value="m">Mantorville</IonSelectOption>
							<IonSelectOption value="m">Maple Grove</IonSelectOption>
							<IonSelectOption value="m">Maple Lake</IonSelectOption>
							<IonSelectOption value="m">Maple Plain</IonSelectOption>
							<IonSelectOption value="m">Mapleton</IonSelectOption>
							<IonSelectOption value="m">Mapleview</IonSelectOption>
							<IonSelectOption value="m">Maplewood</IonSelectOption>
							<IonSelectOption value="m">Marble</IonSelectOption>
							<IonSelectOption value="m">Marietta</IonSelectOption>
							<IonSelectOption value="m">Marine on St. Croix</IonSelectOption>
							<IonSelectOption value="m">Marshall</IonSelectOption>
							<IonSelectOption value="m">Mayer</IonSelectOption>
							<IonSelectOption value="m">Maynard</IonSelectOption>
							<IonSelectOption value="m">Mazeppa</IonSelectOption>
							<IonSelectOption value="m">Meadowlands</IonSelectOption>
							<IonSelectOption value="m">Medford</IonSelectOption>
							<IonSelectOption value="m">Medicine Lake</IonSelectOption>
							<IonSelectOption value="m">Medina</IonSelectOption>
							<IonSelectOption value="m">Meire Grove</IonSelectOption>
							<IonSelectOption value="m">Melrose</IonSelectOption>
							<IonSelectOption value="m">Menahga</IonSelectOption>
							<IonSelectOption value="m">Mendota</IonSelectOption>
							<IonSelectOption value="m">Mendota Heights</IonSelectOption>
							<IonSelectOption value="m">Mentor</IonSelectOption>
							<IonSelectOption value="m">Merriam</IonSelectOption>
							<IonSelectOption value="m">Merrifield</IonSelectOption>
							<IonSelectOption value="m">Middle River</IonSelectOption>
							<IonSelectOption value="m">Miesville</IonSelectOption>
							<IonSelectOption value="m">Milaca</IonSelectOption>
							<IonSelectOption value="m">Milan</IonSelectOption>
							<IonSelectOption value="m">Millerville</IonSelectOption>
							<IonSelectOption value="m">Millville</IonSelectOption>
							<IonSelectOption value="m">Milroy</IonSelectOption>
							<IonSelectOption value="m">Miltona</IonSelectOption>
							<IonSelectOption value="m">Minneapolis</IonSelectOption>
							<IonSelectOption value="m">Minneiska</IonSelectOption>
							<IonSelectOption value="m">Minneota</IonSelectOption>
							<IonSelectOption value="m">Minnesota City</IonSelectOption>
							<IonSelectOption value="m">Minnesota Lake</IonSelectOption>
							<IonSelectOption value="m">Minnetonka</IonSelectOption>
							<IonSelectOption value="m">Minnetonka Beach</IonSelectOption>
							<IonSelectOption value="m">Minnetrista</IonSelectOption>
							<IonSelectOption value="m">Mizpah</IonSelectOption>
							<IonSelectOption value="m">Montevideo</IonSelectOption>
							<IonSelectOption value="m">Montgomery</IonSelectOption>
							<IonSelectOption value="m">Monticello</IonSelectOption>
							<IonSelectOption value="m">Montrose</IonSelectOption>
							<IonSelectOption value="m">Moorhead</IonSelectOption>
							<IonSelectOption value="m">Moose Lake</IonSelectOption>
							<IonSelectOption value="m">Mora</IonSelectOption>
							<IonSelectOption value="m">Morgan</IonSelectOption>
							<IonSelectOption value="m">Morris</IonSelectOption>
							<IonSelectOption value="m">Morristown</IonSelectOption>
							<IonSelectOption value="m">Morton</IonSelectOption>
							<IonSelectOption value="m">Motley</IonSelectOption>
							<IonSelectOption value="m">Mound</IonSelectOption>
							<IonSelectOption value="m">Mounds View</IonSelectOption>
							<IonSelectOption value="m">Mountain Iron</IonSelectOption>
							<IonSelectOption value="m">Mountain Lake</IonSelectOption>
							<IonSelectOption value="m">Murdock</IonSelectOption>
							<IonSelectOption value="m">Myrtle</IonSelectOption>
							<IonSelectOption value="m">Nashua</IonSelectOption>
							<IonSelectOption value="m">Nashwauk</IonSelectOption>
							<IonSelectOption value="m">Nassau</IonSelectOption>
							<IonSelectOption value="m">Nelson</IonSelectOption>
							<IonSelectOption value="m">Nerstrand</IonSelectOption>
							<IonSelectOption value="m">Nevis</IonSelectOption>
							<IonSelectOption value="m">New Auburn</IonSelectOption>
							<IonSelectOption value="m">New Brighton</IonSelectOption>
							<IonSelectOption value="m">New Germany</IonSelectOption>
							<IonSelectOption value="m">New Hope</IonSelectOption>
							<IonSelectOption value="m">New London</IonSelectOption>
							<IonSelectOption value="m">New Market</IonSelectOption>
							<IonSelectOption value="m">New Munich</IonSelectOption>
							<IonSelectOption value="m">New Prague</IonSelectOption>
							<IonSelectOption value="m">New Richland</IonSelectOption>
							<IonSelectOption value="m">New Trier</IonSelectOption>
							<IonSelectOption value="m">New Ulm</IonSelectOption>
							<IonSelectOption value="m">New York Mills</IonSelectOption>
							<IonSelectOption value="m">Newfolden</IonSelectOption>
							<IonSelectOption value="m">Newport</IonSelectOption>
							<IonSelectOption value="m">Nickerson</IonSelectOption>
							<IonSelectOption value="m">Nicollet</IonSelectOption>
							<IonSelectOption value="m">Nielsville</IonSelectOption>
							<IonSelectOption value="m">Nimrod</IonSelectOption>
							<IonSelectOption value="m">Nisswa</IonSelectOption>
							<IonSelectOption value="m">Norcross</IonSelectOption>
							<IonSelectOption value="m">North Branch</IonSelectOption>
							<IonSelectOption value="m">North Mankato</IonSelectOption>
							<IonSelectOption value="m">North Oaks</IonSelectOption>
							<IonSelectOption value="m">North St. Paul</IonSelectOption>
							<IonSelectOption value="m">Northfield</IonSelectOption>
							<IonSelectOption value="m">Northome</IonSelectOption>
							<IonSelectOption value="m">Northrop</IonSelectOption>
							<IonSelectOption value="m">Norwood Young America</IonSelectOption>
							<IonSelectOption value="m">Nowthen</IonSelectOption>
							<IonSelectOption value="m">Oakdale</IonSelectOption>
							<IonSelectOption value="m">Oak Grove</IonSelectOption>
							<IonSelectOption value="m">Oak Park Heights</IonSelectOption>
							<IonSelectOption value="m">Odessa</IonSelectOption>
							<IonSelectOption value="m">Odin</IonSelectOption>
							<IonSelectOption value="m">Ogema</IonSelectOption>
							<IonSelectOption value="m">Ogilvie</IonSelectOption>
							<IonSelectOption value="m">Okabena</IonSelectOption>
							<IonSelectOption value="m">Oklee</IonSelectOption>
							<IonSelectOption value="m">Olivia</IonSelectOption>
							<IonSelectOption value="m">Onamia</IonSelectOption>
							<IonSelectOption value="m">Ormsby</IonSelectOption>
							<IonSelectOption value="m">Orono</IonSelectOption>
							<IonSelectOption value="m">Oronoco</IonSelectOption>
							<IonSelectOption value="m">Orr</IonSelectOption>
							<IonSelectOption value="m">Ortonville</IonSelectOption>
							<IonSelectOption value="m">Osakis</IonSelectOption>
							<IonSelectOption value="m">Oslo</IonSelectOption>
							<IonSelectOption value="m">Osseo</IonSelectOption>
							<IonSelectOption value="m">Ostrander</IonSelectOption>
							<IonSelectOption value="m">Otsego</IonSelectOption>
							<IonSelectOption value="m">Ottertail</IonSelectOption>
							<IonSelectOption value="m">Owatonna</IonSelectOption>
							<IonSelectOption value="m">Palisade</IonSelectOption>
							<IonSelectOption value="m">Park Rapids</IonSelectOption>
							<IonSelectOption value="m">Parkers Prairie</IonSelectOption>
							<IonSelectOption value="m">Paynesville</IonSelectOption>
							<IonSelectOption value="m">Pease</IonSelectOption>
							<IonSelectOption value="m">Pelican Rapids</IonSelectOption>
							<IonSelectOption value="m">Pemberton</IonSelectOption>
							<IonSelectOption value="m">Pennock</IonSelectOption>
							<IonSelectOption value="m">Pequot Lakes</IonSelectOption>
							<IonSelectOption value="m">Perham</IonSelectOption>
							<IonSelectOption value="m">Perley</IonSelectOption>
							<IonSelectOption value="m">Peterson</IonSelectOption>
							<IonSelectOption value="m">Pierz</IonSelectOption>
							<IonSelectOption value="m">Pillager</IonSelectOption>
							<IonSelectOption value="m">Pine City</IonSelectOption>
							<IonSelectOption value="m">Pine Island</IonSelectOption>
							<IonSelectOption value="m">Pine River</IonSelectOption>
							<IonSelectOption value="m">Pine Springs</IonSelectOption>
							<IonSelectOption value="m">Pipestone</IonSelectOption>
							<IonSelectOption value="m">Plainview</IonSelectOption>
							<IonSelectOption value="m">Plato</IonSelectOption>
							<IonSelectOption value="m">Pleasant Lake</IonSelectOption>
							<IonSelectOption value="m">Plummer</IonSelectOption>
							<IonSelectOption value="m">Plymouth</IonSelectOption>
							<IonSelectOption value="m">Porter</IonSelectOption>
							<IonSelectOption value="m">Pratt</IonSelectOption>
							<IonSelectOption value="m">Preston</IonSelectOption>
							<IonSelectOption value="m">Princeton</IonSelectOption>
							<IonSelectOption value="m">Prinsburg</IonSelectOption>
							<IonSelectOption value="m">Prior Lake</IonSelectOption>
							<IonSelectOption value="m">Proctor</IonSelectOption>
							<IonSelectOption value="m">Puposky</IonSelectOption>
							<IonSelectOption value="m">Quamba</IonSelectOption>
							<IonSelectOption value="m">Rochester</IonSelectOption>
							<IonSelectOption value="m">Racine</IonSelectOption>
							<IonSelectOption value="m">Ramsey</IonSelectOption>
							<IonSelectOption value="m">Randall</IonSelectOption>
							<IonSelectOption value="m">Randolph</IonSelectOption>
							<IonSelectOption value="m">Ranier</IonSelectOption>
							<IonSelectOption value="m">Raymond</IonSelectOption>
							<IonSelectOption value="m">Red Lake Falls</IonSelectOption>
							<IonSelectOption value="m">Red Wing</IonSelectOption>
							<IonSelectOption value="m">Redwood Falls</IonSelectOption>
							<IonSelectOption value="m">Regal</IonSelectOption>
							<IonSelectOption value="m">Remer</IonSelectOption>
							<IonSelectOption value="m">Renville</IonSelectOption>
							<IonSelectOption value="m">Revere</IonSelectOption>
							<IonSelectOption value="m">Rice</IonSelectOption>
							<IonSelectOption value="m">Richfield</IonSelectOption>
							<IonSelectOption value="m">Richmond</IonSelectOption>
							<IonSelectOption value="m">Richville</IonSelectOption>
							<IonSelectOption value="m">Riverton</IonSelectOption>
							<IonSelectOption value="m">Robbinsdale</IonSelectOption>
							<IonSelectOption value="m">Rochester</IonSelectOption>
							<IonSelectOption value="m">Rock Creek</IonSelectOption>
							<IonSelectOption value="m">Rockford</IonSelectOption>
							<IonSelectOption value="m">Rockville</IonSelectOption>
							<IonSelectOption value="m">Rogers</IonSelectOption>
							<IonSelectOption value="m">Rollingstone</IonSelectOption>
							<IonSelectOption value="m">Ronneby</IonSelectOption>
							<IonSelectOption value="m">Roosevelt</IonSelectOption>
							<IonSelectOption value="m">Roscoe</IonSelectOption>
							<IonSelectOption value="m">Rose Creek</IonSelectOption>
							<IonSelectOption value="m">Roseau</IonSelectOption>
							<IonSelectOption value="m">Rosemount</IonSelectOption>
							<IonSelectOption value="m">Roseville</IonSelectOption>
							<IonSelectOption value="m">Rothsay</IonSelectOption>
							<IonSelectOption value="m">Round Lake</IonSelectOption>
							<IonSelectOption value="m">Royalton</IonSelectOption>
							<IonSelectOption value="m">Rush City</IonSelectOption>
							<IonSelectOption value="m">Rushford</IonSelectOption>
							<IonSelectOption value="m">Rushford Village</IonSelectOption>
							<IonSelectOption value="m">Rushmore</IonSelectOption>
							<IonSelectOption value="m">Russell</IonSelectOption>
							<IonSelectOption value="m">Ruthton</IonSelectOption>
							<IonSelectOption value="m">Rutledge</IonSelectOption>
							<IonSelectOption value="m">St. Paul, capital of Minnesota</IonSelectOption>
							<IonSelectOption value="m">Sabin</IonSelectOption>
							<IonSelectOption value="m">Sacred Heart</IonSelectOption>
							<IonSelectOption value="m">St. Anthony</IonSelectOption>
							<IonSelectOption value="m">St. Anthony Village</IonSelectOption>
							<IonSelectOption value="m">St. Augusta</IonSelectOption>
							<IonSelectOption value="m">St. Bonifacius</IonSelectOption>
							<IonSelectOption value="m">St. Charles</IonSelectOption>
							<IonSelectOption value="m">St. Clair</IonSelectOption>
							<IonSelectOption value="m">St. Cloud</IonSelectOption>
							<IonSelectOption value="m">St. Francis</IonSelectOption>
							<IonSelectOption value="m">St. Hilaire</IonSelectOption>
							<IonSelectOption value="m">St. James</IonSelectOption>
							<IonSelectOption value="m">St. Joseph</IonSelectOption>
							<IonSelectOption value="m">St. Leo</IonSelectOption>
							<IonSelectOption value="m">St. Louis Park</IonSelectOption>
							<IonSelectOption value="m">St. Martin</IonSelectOption>
							<IonSelectOption value="m">St. Marys Point</IonSelectOption>
							<IonSelectOption value="m">St. Michael</IonSelectOption>
							<IonSelectOption value="m">St. Paul</IonSelectOption>
							<IonSelectOption value="m">St. Paul Park</IonSelectOption>
							<IonSelectOption value="m">St. Peter</IonSelectOption>
							<IonSelectOption value="m">St. Rosa</IonSelectOption>
							<IonSelectOption value="m">St. Stephen</IonSelectOption>
							<IonSelectOption value="m">St. Vincent</IonSelectOption>
							<IonSelectOption value="m">Sanborn</IonSelectOption>
							<IonSelectOption value="m">Sandstone</IonSelectOption>
							<IonSelectOption value="m">Sargeant</IonSelectOption>
							<IonSelectOption value="m">Sartell</IonSelectOption>
							<IonSelectOption value="m">Sauk Centre</IonSelectOption>
							<IonSelectOption value="m">Sauk Rapids</IonSelectOption>
							<IonSelectOption value="m">Savage</IonSelectOption>
							<IonSelectOption value="m">Scandia</IonSelectOption>
							<IonSelectOption value="m">Scanlon</IonSelectOption>
							<IonSelectOption value="m">Seaforth</IonSelectOption>
							<IonSelectOption value="m">Sebeka</IonSelectOption>
							<IonSelectOption value="m">Sedan</IonSelectOption>
							<IonSelectOption value="m">Shafer</IonSelectOption>
							<IonSelectOption value="m">Shakopee</IonSelectOption>
							<IonSelectOption value="m">Shelly</IonSelectOption>
							<IonSelectOption value="m">Sherburn</IonSelectOption>
							<IonSelectOption value="m">Shevlin</IonSelectOption>
							<IonSelectOption value="m">Shoreview</IonSelectOption>
							<IonSelectOption value="m">Shorewood</IonSelectOption>
							<IonSelectOption value="m">Silver Bay</IonSelectOption>
							<IonSelectOption value="m">Silver Lake</IonSelectOption>
							<IonSelectOption value="m">Skyline</IonSelectOption>
							<IonSelectOption value="m">Slayton</IonSelectOption>
							<IonSelectOption value="m">Sleepy Eye</IonSelectOption>
							<IonSelectOption value="m">Sobieski</IonSelectOption>
							<IonSelectOption value="m">Solway</IonSelectOption>
							<IonSelectOption value="m">South Haven</IonSelectOption>
							<IonSelectOption value="m">South St. Paul</IonSelectOption>
							<IonSelectOption value="m">Spicer</IonSelectOption>
							<IonSelectOption value="m">Spring Grove</IonSelectOption>
							<IonSelectOption value="m">Spring Hill</IonSelectOption>
							<IonSelectOption value="m">Spring Lake Park</IonSelectOption>
							<IonSelectOption value="m">Spring Park</IonSelectOption>
							<IonSelectOption value="m">Spring Valley</IonSelectOption>
							<IonSelectOption value="m">Springfield</IonSelectOption>
							<IonSelectOption value="m">Squaw Lake</IonSelectOption>
							<IonSelectOption value="m">Stacy</IonSelectOption>
							<IonSelectOption value="m">Staples</IonSelectOption>
							<IonSelectOption value="m">Starbuck</IonSelectOption>
							<IonSelectOption value="m">Steen</IonSelectOption>
							<IonSelectOption value="m">Stephen</IonSelectOption>
							<IonSelectOption value="m">Stewart</IonSelectOption>
							<IonSelectOption value="m">Stewartville</IonSelectOption>
							<IonSelectOption value="m">Stillwater</IonSelectOption>
							<IonSelectOption value="m">Stockton</IonSelectOption>
							<IonSelectOption value="m">Storden</IonSelectOption>
							<IonSelectOption value="m">Strandquist</IonSelectOption>
							<IonSelectOption value="m">Strathcona</IonSelectOption>
							<IonSelectOption value="m">Sturgeon Lake</IonSelectOption>
							<IonSelectOption value="m">Sunburg</IonSelectOption>
							<IonSelectOption value="m">Sunfish Lake</IonSelectOption>
							<IonSelectOption value="m">Swanville</IonSelectOption>
							<IonSelectOption value="m">Taconite</IonSelectOption>
							<IonSelectOption value="m">Tamarack</IonSelectOption>
							<IonSelectOption value="m">Taopi</IonSelectOption>
							<IonSelectOption value="m">Taunton</IonSelectOption>
							<IonSelectOption value="m">Taylors Falls</IonSelectOption>
							<IonSelectOption value="m">Tenney</IonSelectOption>
							<IonSelectOption value="m">Tenstrike</IonSelectOption>
							<IonSelectOption value="m">Thief River Falls</IonSelectOption>
							<IonSelectOption value="m">Thomson</IonSelectOption>
							<IonSelectOption value="m">Tintah</IonSelectOption>
							<IonSelectOption value="m">Tonka Bay</IonSelectOption>
							<IonSelectOption value="m">Tower</IonSelectOption>
							<IonSelectOption value="m">Tracy</IonSelectOption>
							<IonSelectOption value="m">Trail</IonSelectOption>
							<IonSelectOption value="m">Trimont</IonSelectOption>
							<IonSelectOption value="m">Trommald</IonSelectOption>
							<IonSelectOption value="m">Trosky</IonSelectOption>
							<IonSelectOption value="m">Truman</IonSelectOption>
							<IonSelectOption value="m">Turtle River</IonSelectOption>
							<IonSelectOption value="m">Twin Lakes</IonSelectOption>
							<IonSelectOption value="m">Twin Valley</IonSelectOption>
							<IonSelectOption value="m">Two Harbors</IonSelectOption>
							<IonSelectOption value="m">Tyler</IonSelectOption>
							<IonSelectOption value="m">Ulen</IonSelectOption>
							<IonSelectOption value="m">Underwood</IonSelectOption>
							<IonSelectOption value="m">Upsala</IonSelectOption>
							<IonSelectOption value="m">Urbank</IonSelectOption>
							<IonSelectOption value="m">Utica</IonSelectOption>
							<IonSelectOption value="m">Vadnais Heights</IonSelectOption>
							<IonSelectOption value="m">Vergas</IonSelectOption>
							<IonSelectOption value="m">Vermillion</IonSelectOption>
							<IonSelectOption value="m">Verndale</IonSelectOption>
							<IonSelectOption value="m">Vernon Center</IonSelectOption>
							<IonSelectOption value="m">Vesta</IonSelectOption>
							<IonSelectOption value="m">Victoria</IonSelectOption>
							<IonSelectOption value="m">Viking</IonSelectOption>
							<IonSelectOption value="m">Villard</IonSelectOption>
							<IonSelectOption value="m">Vining</IonSelectOption>
							<IonSelectOption value="m">Virginia</IonSelectOption>
							<IonSelectOption value="m">Wabasha</IonSelectOption>
							<IonSelectOption value="m">Wabasso</IonSelectOption>
							<IonSelectOption value="m">Waconia</IonSelectOption>
							<IonSelectOption value="m">Wadena</IonSelectOption>
							<IonSelectOption value="m">Wahkon</IonSelectOption>
							<IonSelectOption value="m">Waite Park</IonSelectOption>
							<IonSelectOption value="m">Waldorf</IonSelectOption>
							<IonSelectOption value="m">Walker</IonSelectOption>
							<IonSelectOption value="m">Walnut Grove</IonSelectOption>
							<IonSelectOption value="m">Walters</IonSelectOption>
							<IonSelectOption value="m">Waltham</IonSelectOption>
							<IonSelectOption value="m">Wanamingo</IonSelectOption>
							<IonSelectOption value="m">Wanda</IonSelectOption>
							<IonSelectOption value="m">Warba</IonSelectOption>
							<IonSelectOption value="m">Warren</IonSelectOption>
							<IonSelectOption value="m">Warroad</IonSelectOption>
							<IonSelectOption value="m">Waseca</IonSelectOption>
							<IonSelectOption value="m">Watertown</IonSelectOption>
							<IonSelectOption value="m">Waterville</IonSelectOption>
							<IonSelectOption value="m">Watkins</IonSelectOption>
							<IonSelectOption value="m">Watson</IonSelectOption>
							<IonSelectOption value="m">Waubun</IonSelectOption>
							<IonSelectOption value="m">Waverly</IonSelectOption>
							<IonSelectOption value="m">Wayzata</IonSelectOption>
							<IonSelectOption value="m">Welcome</IonSelectOption>
							<IonSelectOption value="m">Wells</IonSelectOption>
							<IonSelectOption value="m">Wendell</IonSelectOption>
							<IonSelectOption value="m">West Concord</IonSelectOption>
							<IonSelectOption value="m">West St. Paul</IonSelectOption>
							<IonSelectOption value="m">West Union</IonSelectOption>
							<IonSelectOption value="m">Westbrook</IonSelectOption>
							<IonSelectOption value="m">Westport</IonSelectOption>
							<IonSelectOption value="m">Whalan</IonSelectOption>
							<IonSelectOption value="m">Wheaton</IonSelectOption>
							<IonSelectOption value="m">White Bear Lake</IonSelectOption>
							<IonSelectOption value="m">Wilder</IonSelectOption>
							<IonSelectOption value="m">Willernie</IonSelectOption>
							<IonSelectOption value="m">Williams</IonSelectOption>
							<IonSelectOption value="m">Willmar</IonSelectOption>
							<IonSelectOption value="m">Willow River</IonSelectOption>
							<IonSelectOption value="m">Wilmont</IonSelectOption>
							<IonSelectOption value="m">Wilton</IonSelectOption>
							<IonSelectOption value="m">Windom</IonSelectOption>
							<IonSelectOption value="m">Winger</IonSelectOption>
							<IonSelectOption value="m">Winnebago</IonSelectOption>
							<IonSelectOption value="m">Winona</IonSelectOption>
							<IonSelectOption value="m">Winsted</IonSelectOption>
							<IonSelectOption value="m">Winthrop</IonSelectOption>
							<IonSelectOption value="m">Winton</IonSelectOption>
							<IonSelectOption value="m">Wolf Lake</IonSelectOption>
							<IonSelectOption value="m">Wolverton</IonSelectOption>
							<IonSelectOption value="m">Wood Lake</IonSelectOption>
							<IonSelectOption value="m">Woodbury</IonSelectOption>
							<IonSelectOption value="m">Woodland</IonSelectOption>
							<IonSelectOption value="m">Woodstock</IonSelectOption>
							<IonSelectOption value="m">Worthington</IonSelectOption>
						</IonList>
					</IonSelect>
				</IonItem>
			</IonContent>
		</IonPage>
	);
};

export default Tab3Page;
