import React from 'react';
import {
	IonItem,
	IonLabel,
	IonSelect,
	IonSelectOption,
	IonContent,
	IonHeader,
	IonToolbar,
	IonPage,
	IonTitle,
	IonList,
	} from '@ionic/react';

const Tab3Page: React.FC = () => {
	return (
		<IonPage>
			<IonHeader>
				<IonToolbar>
					<IonTitle>Settings</IonTitle>
				</IonToolbar>
			</IonHeader>
			<IonContent>
				<IonItem>
					<IonLabel>City</IonLabel>
					<IonSelect placeholder="Select One">
						<IonList>
							<IonSelectOption value="No Selection">No Selection</IonSelectOption>
							<IonSelectOption value="Ada">Ada</IonSelectOption>
							<IonSelectOption value="Adams">Adams</IonSelectOption>
							<IonSelectOption value="Adrian">Adrian</IonSelectOption>
							<IonSelectOption value="Afton">Afton</IonSelectOption>
							<IonSelectOption value="Aitkin">Aitkin</IonSelectOption>
							<IonSelectOption value="Akeley">Akeley</IonSelectOption>
							<IonSelectOption value="Albany">Albany</IonSelectOption>
							<IonSelectOption value="Albert Lea">Albert Lea</IonSelectOption>
							<IonSelectOption value="Alberta">Alberta</IonSelectOption>
							<IonSelectOption value="Albertville">Albertville</IonSelectOption>
							<IonSelectOption value="Alden">Alden</IonSelectOption>
							<IonSelectOption value="Aldrich">Aldrich</IonSelectOption>
							<IonSelectOption value="Alexandria">Alexandria</IonSelectOption>
							<IonSelectOption value="Alpha">Alpha</IonSelectOption>
							<IonSelectOption value="Altura">Altura</IonSelectOption>
							<IonSelectOption value="Alvarado">Alvarado</IonSelectOption>
							<IonSelectOption value="Amboy">Amboy</IonSelectOption>
							<IonSelectOption value="Andover">Andover</IonSelectOption>
							<IonSelectOption value="Annandale">Annandale</IonSelectOption>
							<IonSelectOption value="Anoka">Anoka</IonSelectOption>
							<IonSelectOption value="Apple Valley">Apple Valley</IonSelectOption>
							<IonSelectOption value="Appleton">Appleton</IonSelectOption>
							<IonSelectOption value="Arco">Arco</IonSelectOption>
							<IonSelectOption value="Arden Hills">Arden Hills</IonSelectOption>
							<IonSelectOption value="Argyle">Argyle</IonSelectOption>
							<IonSelectOption value="Arlington">Arlington</IonSelectOption>
							<IonSelectOption value="Ashby">Ashby</IonSelectOption>
							<IonSelectOption value="Askov">Askov</IonSelectOption>
							<IonSelectOption value="Atwater">Atwater</IonSelectOption>
							<IonSelectOption value="Audubon">Audubon</IonSelectOption>
							<IonSelectOption value="Aurora">Aurora</IonSelectOption>
							<IonSelectOption value="Austin">Austin</IonSelectOption>
							<IonSelectOption value="Avoca">Avoca</IonSelectOption>
							<IonSelectOption value="Avon">Avon</IonSelectOption>
							<IonSelectOption value="Bloomington">Bloomington</IonSelectOption>
							<IonSelectOption value="Babbitt">Babbitt</IonSelectOption>
							<IonSelectOption value="Backus">Backus</IonSelectOption>
							<IonSelectOption value="Badger">Badger</IonSelectOption>
							<IonSelectOption value="Bagley">Bagley</IonSelectOption>
							<IonSelectOption value="Balaton">Balaton</IonSelectOption>
							<IonSelectOption value="Barnesville">Barnesville</IonSelectOption>
							<IonSelectOption value="Barnum">Barnum</IonSelectOption>
							<IonSelectOption value="Barrett">Barrett</IonSelectOption>
							<IonSelectOption value="Barry">Barry</IonSelectOption>
							<IonSelectOption value="Battle Lake">Battle Lake</IonSelectOption>
							<IonSelectOption value="Baudette">Baudette</IonSelectOption>
							<IonSelectOption value="Baxter">Baxter</IonSelectOption>
							<IonSelectOption value="Bayport">Bayport</IonSelectOption>
							<IonSelectOption value="Beardsley">Beardsley</IonSelectOption>
							<IonSelectOption value="Beaver Bay">Beaver Bay</IonSelectOption>
							<IonSelectOption value="Beaver Creek">Beaver Creek</IonSelectOption>
							<IonSelectOption value="Becker">Becker</IonSelectOption>
							<IonSelectOption value="Bejou">Bejou</IonSelectOption>
							<IonSelectOption value="Belgrade">Belgrade</IonSelectOption>
							<IonSelectOption value="Belle Plaine">Belle Plaine</IonSelectOption>
							<IonSelectOption value="Bellechester">Bellechester</IonSelectOption>
							<IonSelectOption value="Bellingham">Bellingham</IonSelectOption>
							<IonSelectOption value="Beltrami">Beltrami</IonSelectOption>
							<IonSelectOption value="Belview">Belview</IonSelectOption>
							<IonSelectOption value="Bemidji">Bemidji</IonSelectOption>
							<IonSelectOption value="Bena">Bena</IonSelectOption>
							<IonSelectOption value="Benson">Benson</IonSelectOption>
							<IonSelectOption value="Beroun">Beroun</IonSelectOption>
							<IonSelectOption value="Bertha">Bertha</IonSelectOption>
							<IonSelectOption value="Bethel">Bethel</IonSelectOption>
							<IonSelectOption value="Big Falls">Big Falls</IonSelectOption>
							<IonSelectOption value="Big Lake">Big Lake</IonSelectOption>
							<IonSelectOption value="Bigelow">Bigelow</IonSelectOption>
							<IonSelectOption value="Bigfork">Bigfork</IonSelectOption>
							<IonSelectOption value="Bingham Lake">Bingham Lake</IonSelectOption>
							<IonSelectOption value="Birchwood Village">Birchwood Village</IonSelectOption>
							<IonSelectOption value="Bird Island">Bird Island</IonSelectOption>
							<IonSelectOption value="Biscay">Biscay</IonSelectOption>
							<IonSelectOption value="Biwabik">Biwabik</IonSelectOption>
							<IonSelectOption value="Blackduck">Blackduck</IonSelectOption>
							<IonSelectOption value="Blaine">Blaine</IonSelectOption>
							<IonSelectOption value="Blomkest">Blomkest</IonSelectOption>
							<IonSelectOption value="Blooming Prairie">Blooming Prairie</IonSelectOption>
							<IonSelectOption value="Bloomington">Bloomington</IonSelectOption>
							<IonSelectOption value="Blue Earth">Blue Earth</IonSelectOption>
							<IonSelectOption value="Bluffton">Bluffton</IonSelectOption>
							<IonSelectOption value="Bock">Bock</IonSelectOption>
							<IonSelectOption value="Borup">Borup</IonSelectOption>
							<IonSelectOption value="Bovey">Bovey</IonSelectOption>
							<IonSelectOption value="Bowlus">Bowlus</IonSelectOption>
							<IonSelectOption value="Boy River">Boy River</IonSelectOption>
							<IonSelectOption value="Boyd">Boyd</IonSelectOption>
							<IonSelectOption value="Braham">Braham</IonSelectOption>
							<IonSelectOption value="Brainerd">Brainerd</IonSelectOption>
							<IonSelectOption value="Brandon">Brandon</IonSelectOption>
							<IonSelectOption value="Breckenridge">Breckenridge</IonSelectOption>
							<IonSelectOption value="Breezy Point">Breezy Point</IonSelectOption>
							<IonSelectOption value="Brewster">Brewster</IonSelectOption>
							<IonSelectOption value="Bricelyn">Bricelyn</IonSelectOption>
							<IonSelectOption value="Brook Park">Brook Park</IonSelectOption>
							<IonSelectOption value="Brooklyn Center">Brooklyn Center</IonSelectOption>
							<IonSelectOption value="Brooklyn Park">Brooklyn Park</IonSelectOption>
							<IonSelectOption value="Brooks">Brooks</IonSelectOption>
							<IonSelectOption value="Brookston">Brookston</IonSelectOption>
							<IonSelectOption value="Brooten">Brooten</IonSelectOption>
							<IonSelectOption value="Browerville">Browerville</IonSelectOption>
							<IonSelectOption value="Browns Valley">Browns Valley</IonSelectOption>
							<IonSelectOption value="Brownsdale">Brownsdale</IonSelectOption>
							<IonSelectOption value="Brownsville">Brownsville</IonSelectOption>
							<IonSelectOption value="Brownton">Brownton</IonSelectOption>
							<IonSelectOption value="Bruno">Bruno</IonSelectOption>
							<IonSelectOption value="Buckman">Buckman</IonSelectOption>
							<IonSelectOption value="Buffalo">Buffalo</IonSelectOption>
							<IonSelectOption value="Buffalo Lake">Buffalo Lake</IonSelectOption>
							<IonSelectOption value="Buhl">Buhl</IonSelectOption>
							<IonSelectOption value="Burnsville">Burnsville</IonSelectOption>
							<IonSelectOption value="Burtrum">Burtrum</IonSelectOption>
							<IonSelectOption value="Butterfield">Butterfield</IonSelectOption>
							<IonSelectOption value="Byron">Byron</IonSelectOption>
							<IonSelectOption value="Caledonia">Caledonia</IonSelectOption>
							<IonSelectOption value="Callaway">Callaway</IonSelectOption>
							<IonSelectOption value="Calumet">Calumet</IonSelectOption>
							<IonSelectOption value="Cambridge">Cambridge</IonSelectOption>
							<IonSelectOption value="Campbell">Campbell</IonSelectOption>
							<IonSelectOption value="Canby">Canby</IonSelectOption>
							<IonSelectOption value="Cannon Falls">Cannon Falls</IonSelectOption>
							<IonSelectOption value="Canton">Canton</IonSelectOption>
							<IonSelectOption value="Carlos">Carlos</IonSelectOption>
							<IonSelectOption value="Carlton">Carlton</IonSelectOption>
							<IonSelectOption value="Carver">Carver</IonSelectOption>
							<IonSelectOption value="Cass Lake">Cass Lake</IonSelectOption>
							<IonSelectOption value="Cedar Mills">Cedar Mills</IonSelectOption>
							<IonSelectOption value="Center City">Center City</IonSelectOption>
							<IonSelectOption value="Centerville">Centerville</IonSelectOption>
							<IonSelectOption value="Ceylon">Ceylon</IonSelectOption>
							<IonSelectOption value="Champlin">Champlin</IonSelectOption>
							<IonSelectOption value="Chandler">Chandler</IonSelectOption>
							<IonSelectOption value="Chanhassen">Chanhassen</IonSelectOption>
							<IonSelectOption value="Chaska">Chaska</IonSelectOption>
							<IonSelectOption value="Chatfield">Chatfield</IonSelectOption>
							<IonSelectOption value="Chickamaw Beach">Chickamaw Beach</IonSelectOption>
							<IonSelectOption value="Chisago City">Chisago City</IonSelectOption>
							<IonSelectOption value="Chisholm">Chisholm</IonSelectOption>
							<IonSelectOption value="Chokio">Chokio</IonSelectOption>
							<IonSelectOption value="Circle Pines">Circle Pines</IonSelectOption>
							<IonSelectOption value="Clara City">Clara City</IonSelectOption>
							<IonSelectOption value="Claremont">Claremont</IonSelectOption>
							<IonSelectOption value="Clarissa">Clarissa</IonSelectOption>
							<IonSelectOption value="Clarkfield">Clarkfield</IonSelectOption>
							<IonSelectOption value="Clarks Grove">Clarks Grove</IonSelectOption>
							<IonSelectOption value="Clear Lake">Clear Lake</IonSelectOption>
							<IonSelectOption value="Clearbrook">Clearbrook</IonSelectOption>
							<IonSelectOption value="Clearwater">Clearwater</IonSelectOption>
							<IonSelectOption value="Clements">Clements</IonSelectOption>
							<IonSelectOption value="Cleveland">Cleveland</IonSelectOption>
							<IonSelectOption value="Climax">Climax</IonSelectOption>
							<IonSelectOption value="Clinton">Clinton</IonSelectOption>
							<IonSelectOption value="Clitherall">Clitherall</IonSelectOption>
							<IonSelectOption value="Clontarf">Clontarf</IonSelectOption>
							<IonSelectOption value="Cloquet">Cloquet</IonSelectOption>
							<IonSelectOption value="Coates">Coates</IonSelectOption>
							<IonSelectOption value="Cobden">Cobden</IonSelectOption>
							<IonSelectOption value="Cohasset">Cohasset</IonSelectOption>
							<IonSelectOption value="Cokato">Cokato</IonSelectOption>
							<IonSelectOption value="Cold Spring">Cold Spring</IonSelectOption>
							<IonSelectOption value="Coleraine">Coleraine</IonSelectOption>
							<IonSelectOption value="Collegeville">Collegeville</IonSelectOption>
							<IonSelectOption value="Cologne">Cologne</IonSelectOption>
							<IonSelectOption value="Columbia Heights">Columbia Heights</IonSelectOption>
							<IonSelectOption value="Columbus">Columbus</IonSelectOption>
							<IonSelectOption value="Comfrey">Comfrey</IonSelectOption>
							<IonSelectOption value="Comstock">Comstock</IonSelectOption>
							<IonSelectOption value="Conger">Conger</IonSelectOption>
							<IonSelectOption value="Cook">Cook</IonSelectOption>
							<IonSelectOption value="Coon Rapids">Coon Rapids</IonSelectOption>
							<IonSelectOption value="Corcoran">Corcoran</IonSelectOption>
							<IonSelectOption value="Correll">Correll</IonSelectOption>
							<IonSelectOption value="Cosmos">Cosmos</IonSelectOption>
							<IonSelectOption value="Cottage Grove">Cottage Grove</IonSelectOption>
							<IonSelectOption value="Cottonwood">Cottonwood</IonSelectOption>
							<IonSelectOption value="Courtland">Courtland</IonSelectOption>
							<IonSelectOption value="Cromwell">Cromwell</IonSelectOption>
							<IonSelectOption value="Crookston">Crookston</IonSelectOption>
							<IonSelectOption value="Crosby">Crosby</IonSelectOption>
							<IonSelectOption value="Crosslake">Crosslake</IonSelectOption>
							<IonSelectOption value="Crystal">Crystal</IonSelectOption>
							<IonSelectOption value="Currie">Currie</IonSelectOption>
							<IonSelectOption value="Cuyuna">Cuyuna</IonSelectOption>
							<IonSelectOption value="Cyrus">Cyrus</IonSelectOption>
							<IonSelectOption value="Duluth">Duluth</IonSelectOption>
							<IonSelectOption value="Dakota">Dakota</IonSelectOption>
							<IonSelectOption value="Dalton">Dalton</IonSelectOption>
							<IonSelectOption value="Danube">Danube</IonSelectOption>
							<IonSelectOption value="Danvers">Danvers</IonSelectOption>
							<IonSelectOption value="Darfur">Darfur</IonSelectOption>
							<IonSelectOption value="Darwin">Darwin</IonSelectOption>
							<IonSelectOption value="Dassel">Dassel</IonSelectOption>
							<IonSelectOption value="Dawson">Dawson</IonSelectOption>
							<IonSelectOption value="Dayton">Dayton</IonSelectOption>
							<IonSelectOption value="De Graff">De Graff</IonSelectOption>
							<IonSelectOption value="Deephaven">Deephaven</IonSelectOption>
							<IonSelectOption value="Deer Creek">Deer Creek</IonSelectOption>
							<IonSelectOption value="Deer River">Deer River</IonSelectOption>
							<IonSelectOption value="Deerwood">Deerwood</IonSelectOption>
							<IonSelectOption value="Delano">Delano</IonSelectOption>
							<IonSelectOption value="Delavan">Delavan</IonSelectOption>
							<IonSelectOption value="Delft">Delft</IonSelectOption>
							<IonSelectOption value="Delhi">Delhi</IonSelectOption>
							<IonSelectOption value="Dellwood">Dellwood</IonSelectOption>
							<IonSelectOption value="Denham">Denham</IonSelectOption>
							<IonSelectOption value="Dennison">Dennison</IonSelectOption>
							<IonSelectOption value="Dent">Dent</IonSelectOption>
							<IonSelectOption value="Detroit Lakes">Detroit Lakes</IonSelectOption>
							<IonSelectOption value="Dexter">Dexter</IonSelectOption>
							<IonSelectOption value="Dilworth">Dilworth</IonSelectOption>
							<IonSelectOption value="Dodge Center">Dodge Center</IonSelectOption>
							<IonSelectOption value="Donaldson">Donaldson</IonSelectOption>
							<IonSelectOption value="Donnelly">Donnelly</IonSelectOption>
							<IonSelectOption value="Doran">Doran</IonSelectOption>
							<IonSelectOption value="Dover">Dover</IonSelectOption>
							<IonSelectOption value="Dovray">Dovray</IonSelectOption>
							<IonSelectOption value="Duluth">Duluth</IonSelectOption>
							<IonSelectOption value="Dumont">Dumont</IonSelectOption>
							<IonSelectOption value="Dundas">Dundas</IonSelectOption>
							<IonSelectOption value="Dundee">Dundee</IonSelectOption>
							<IonSelectOption value="Eagan">Eagan</IonSelectOption>
							<IonSelectOption value="Eagle Bend">Eagle Bend</IonSelectOption>
							<IonSelectOption value="Eagle Lake">Eagle Lake</IonSelectOption>
							<IonSelectOption value="East Bethel">East Bethel</IonSelectOption>
							<IonSelectOption value="East Grand Forks">East Grand Forks</IonSelectOption>
							<IonSelectOption value="East Gull Lake">East Gull Lake</IonSelectOption>
							<IonSelectOption value="Easton">Easton</IonSelectOption>
							<IonSelectOption value="Echo">Echo</IonSelectOption>
							<IonSelectOption value="Eden Prairie">Eden Prairie</IonSelectOption>
							<IonSelectOption value="Eden Valley">Eden Valley</IonSelectOption>
							<IonSelectOption value="Edgerton">Edgerton</IonSelectOption>
							<IonSelectOption value="Edina">Edina</IonSelectOption>
							<IonSelectOption value="Effie">Effie</IonSelectOption>
							<IonSelectOption value="Eitzen">Eitzen</IonSelectOption>
							<IonSelectOption value="Elba">Elba</IonSelectOption>
							<IonSelectOption value="Elbow Lake">Elbow Lake</IonSelectOption>
							<IonSelectOption value="Elgin">Elgin</IonSelectOption>
							<IonSelectOption value="Elizabeth">Elizabeth</IonSelectOption>
							<IonSelectOption value="Elk River">Elk River</IonSelectOption>
							<IonSelectOption value="Elko">Elko</IonSelectOption>
							<IonSelectOption value="Elkton">Elkton</IonSelectOption>
							<IonSelectOption value="Ellendale">Ellendale</IonSelectOption>
							<IonSelectOption value="Ellsworth">Ellsworth</IonSelectOption>
							<IonSelectOption value="Elmdale">Elmdale</IonSelectOption>
							<IonSelectOption value="Elmore">Elmore</IonSelectOption>
							<IonSelectOption value="Elrosa">Elrosa</IonSelectOption>
							<IonSelectOption value="Ely">Ely</IonSelectOption>
							<IonSelectOption value="Elysian">Elysian</IonSelectOption>
							<IonSelectOption value="Emily">Emily</IonSelectOption>
							<IonSelectOption value="Emmons">Emmons</IonSelectOption>
							<IonSelectOption value="Erhard">Erhard</IonSelectOption>
							<IonSelectOption value="Erskine">Erskine</IonSelectOption>
							<IonSelectOption value="Evan">Evan</IonSelectOption>
							<IonSelectOption value="Evansville">Evansville</IonSelectOption>
							<IonSelectOption value="Eveleth">Eveleth</IonSelectOption>
							<IonSelectOption value="Excelsior">Excelsior</IonSelectOption>
							<IonSelectOption value="Eyota">Eyota</IonSelectOption>
							<IonSelectOption value="Fairfax">Fairfax</IonSelectOption>
							<IonSelectOption value="Fairmont">Fairmont</IonSelectOption>
							<IonSelectOption value="Falcon Heights">Falcon Heights</IonSelectOption>
							<IonSelectOption value="Faribault">Faribault</IonSelectOption>
							<IonSelectOption value="Farming">Farming</IonSelectOption>
							<IonSelectOption value="Farmington">Farmington</IonSelectOption>
							<IonSelectOption value="Farwell">Farwell</IonSelectOption>
							<IonSelectOption value="Federal Dam">Federal Dam</IonSelectOption>
							<IonSelectOption value="Felton">Felton</IonSelectOption>
							<IonSelectOption value="Fergus Falls">Fergus Falls</IonSelectOption>
							<IonSelectOption value="Fertile">Fertile</IonSelectOption>
							<IonSelectOption value="Fifty Lakes">Fifty Lakes</IonSelectOption>
							<IonSelectOption value="Finlayson">Finlayson</IonSelectOption>
							<IonSelectOption value="Fisher">Fisher</IonSelectOption>
							<IonSelectOption value="Flensburg">Flensburg</IonSelectOption>
							<IonSelectOption value="Floodwood">Floodwood</IonSelectOption>
							<IonSelectOption value="Florence">Florence</IonSelectOption>
							<IonSelectOption value="Foley">Foley</IonSelectOption>
							<IonSelectOption value="Forada">Forada</IonSelectOption>
							<IonSelectOption value="Forest Lake">Forest Lake</IonSelectOption>
							<IonSelectOption value="Foreston">Foreston</IonSelectOption>
							<IonSelectOption value="Fort Ripley">Fort Ripley</IonSelectOption>
							<IonSelectOption value="Fosston">Fosston</IonSelectOption>
							<IonSelectOption value="Fountain">Fountain</IonSelectOption>
							<IonSelectOption value="Foxhome">Foxhome</IonSelectOption>
							<IonSelectOption value="Franklin">Franklin</IonSelectOption>
							<IonSelectOption value="Frazee">Frazee</IonSelectOption>
							<IonSelectOption value="Freeborn">Freeborn</IonSelectOption>
							<IonSelectOption value="Freeport">Freeport</IonSelectOption>
							<IonSelectOption value="Fridley">Fridley</IonSelectOption>
							<IonSelectOption value="Frost">Frost</IonSelectOption>
							<IonSelectOption value="Fulda">Fulda</IonSelectOption>
							<IonSelectOption value="Funkley">Funkley</IonSelectOption>
							<IonSelectOption value="Garfield">Garfield</IonSelectOption>
							<IonSelectOption value="Garrison">Garrison</IonSelectOption>
							<IonSelectOption value="Garvin">Garvin</IonSelectOption>
							<IonSelectOption value="Gary">Gary</IonSelectOption>
							<IonSelectOption value="Gaylord">Gaylord</IonSelectOption>
							<IonSelectOption value="Gem Lake">Gem Lake</IonSelectOption>
							<IonSelectOption value="Geneva">Geneva</IonSelectOption>
							<IonSelectOption value="Genola">Genola</IonSelectOption>
							<IonSelectOption value="Georgetown">Georgetown</IonSelectOption>
							<IonSelectOption value="Ghent">Ghent</IonSelectOption>
							<IonSelectOption value="Gibbon">Gibbon</IonSelectOption>
							<IonSelectOption value="Gilbert">Gilbert</IonSelectOption>
							<IonSelectOption value="Gilman">Gilman</IonSelectOption>
							<IonSelectOption value="Glencoe">Glencoe</IonSelectOption>
							<IonSelectOption value="Glenville">Glenville</IonSelectOption>
							<IonSelectOption value="Glenwood">Glenwood</IonSelectOption>
							<IonSelectOption value="Glyndon">Glyndon</IonSelectOption>
							<IonSelectOption value="Golden Valley">Golden Valley</IonSelectOption>
							<IonSelectOption value="Gonvick">Gonvick</IonSelectOption>
							<IonSelectOption value="Good Thunder">Good Thunder</IonSelectOption>
							<IonSelectOption value="Goodhue">Goodhue</IonSelectOption>
							<IonSelectOption value="Goodridge">Goodridge</IonSelectOption>
							<IonSelectOption value="Goodview">Goodview</IonSelectOption>
							<IonSelectOption value="Graceville">Graceville</IonSelectOption>
							<IonSelectOption value="Granada">Granada</IonSelectOption>
							<IonSelectOption value="Grand Marais">Grand Marais</IonSelectOption>
							<IonSelectOption value="Grand Meadow">Grand Meadow</IonSelectOption>
							<IonSelectOption value="Grand Rapids">Grand Rapids</IonSelectOption>
							<IonSelectOption value="Granite Falls">Granite Falls</IonSelectOption>
							<IonSelectOption value="Grant">Grant</IonSelectOption>
							<IonSelectOption value="Grasston">Grasston</IonSelectOption>
							<IonSelectOption value="Green Isle">Green Isle</IonSelectOption>
							<IonSelectOption value="Greenbush">Greenbush</IonSelectOption>
							<IonSelectOption value="Greenfield">Greenfield</IonSelectOption>
							<IonSelectOption value="Greenwald">Greenwald</IonSelectOption>
							<IonSelectOption value="Greenwood">Greenwood</IonSelectOption>
							<IonSelectOption value="Grey Eagle">Grey Eagle</IonSelectOption>
							<IonSelectOption value="Grove City">Grove City</IonSelectOption>
							<IonSelectOption value="Grygla">Grygla</IonSelectOption>
							<IonSelectOption value="Gully">Gully</IonSelectOption>
							<IonSelectOption value="Hackensack">Hackensack</IonSelectOption>
							<IonSelectOption value="Hadley">Hadley</IonSelectOption>
							<IonSelectOption value="Hallock">Hallock</IonSelectOption>
							<IonSelectOption value="Halma">Halma</IonSelectOption>
							<IonSelectOption value="Halstad">Halstad</IonSelectOption>
							<IonSelectOption value="Ham Lake">Ham Lake</IonSelectOption>
							<IonSelectOption value="Hamburg">Hamburg</IonSelectOption>
							<IonSelectOption value="Hammond">Hammond</IonSelectOption>
							<IonSelectOption value="Hampton">Hampton</IonSelectOption>
							<IonSelectOption value="Hancock">Hancock</IonSelectOption>
							<IonSelectOption value="Hanley Falls">Hanley Falls</IonSelectOption>
							<IonSelectOption value="Hanover">Hanover</IonSelectOption>
							<IonSelectOption value="Hanska">Hanska</IonSelectOption>
							<IonSelectOption value="Harding">Harding</IonSelectOption>
							<IonSelectOption value="Hardwick">Hardwick</IonSelectOption>
							<IonSelectOption value="Harmony">Harmony</IonSelectOption>
							<IonSelectOption value="Harris">Harris</IonSelectOption>
							<IonSelectOption value="Hartland">Hartland</IonSelectOption>
							<IonSelectOption value="Hastings">Hastings</IonSelectOption>
							<IonSelectOption value="Hatfield">Hatfield</IonSelectOption>
							<IonSelectOption value="Hawley">Hawley</IonSelectOption>
							<IonSelectOption value="Hayfield">Hayfield</IonSelectOption>
							<IonSelectOption value="Hayward">Hayward</IonSelectOption>
							<IonSelectOption value="Hazel Run">Hazel Run</IonSelectOption>
							<IonSelectOption value="Hector">Hector</IonSelectOption>
							<IonSelectOption value="Heidelberg">Heidelberg</IonSelectOption>
							<IonSelectOption value="Henderson">Henderson</IonSelectOption>
							<IonSelectOption value="Hendricks">Hendricks</IonSelectOption>
							<IonSelectOption value="Hendrum">Hendrum</IonSelectOption>
							<IonSelectOption value="Henning">Henning</IonSelectOption>
							<IonSelectOption value="Henriette">Henriette</IonSelectOption>
							<IonSelectOption value="Herman">Herman</IonSelectOption>
							<IonSelectOption value="Hermantown">Hermantown</IonSelectOption>
							<IonSelectOption value="Heron Lake">Heron Lake</IonSelectOption>
							<IonSelectOption value="Hewitt">Hewitt</IonSelectOption>
							<IonSelectOption value="Hibbing">Hibbing</IonSelectOption>
							<IonSelectOption value="Hill City">Hill City</IonSelectOption>
							<IonSelectOption value="Hillman">Hillman</IonSelectOption>
							<IonSelectOption value="Hills">Hills</IonSelectOption>
							<IonSelectOption value="Hilltop">Hilltop</IonSelectOption>
							<IonSelectOption value="Hinckley">Hinckley</IonSelectOption>
							<IonSelectOption value="Hitterdal">Hitterdal</IonSelectOption>
							<IonSelectOption value="Hoffman">Hoffman</IonSelectOption>
							<IonSelectOption value="Hokah">Hokah</IonSelectOption>
							<IonSelectOption value="Holdingford">Holdingford</IonSelectOption>
							<IonSelectOption value="Holland">Holland</IonSelectOption>
							<IonSelectOption value="Hollandale">Hollandale</IonSelectOption>
							<IonSelectOption value="Holloway">Holloway</IonSelectOption>
							<IonSelectOption value="Holt">Holt</IonSelectOption>
							<IonSelectOption value="Hopkins">Hopkins</IonSelectOption>
							<IonSelectOption value="Houston">Houston</IonSelectOption>
							<IonSelectOption value="Howard Lake">Howard Lake</IonSelectOption>
							<IonSelectOption value="Hoyt Lakes">Hoyt Lakes</IonSelectOption>
							<IonSelectOption value="Hugo">Hugo</IonSelectOption>
							<IonSelectOption value="Humboldt">Humboldt</IonSelectOption>
							<IonSelectOption value="Hutchinson">Hutchinson</IonSelectOption>
							<IonSelectOption value="Ihlen">Ihlen</IonSelectOption>
							<IonSelectOption value="Independence">Independence</IonSelectOption>
							<IonSelectOption value="International Falls">International Falls</IonSelectOption>
							<IonSelectOption value="Inver Grove Heights">Inver Grove Heights</IonSelectOption>
							<IonSelectOption value="Iona">Iona</IonSelectOption>
							<IonSelectOption value="Iron Junction">Iron Junction</IonSelectOption>
							<IonSelectOption value="Ironton">Ironton</IonSelectOption>
							<IonSelectOption value="Isanti">Isanti</IonSelectOption>
							<IonSelectOption value="Isle">Isle</IonSelectOption>
							<IonSelectOption value="Ivanhoe">Ivanhoe</IonSelectOption>
							<IonSelectOption value="Jackson">Jackson</IonSelectOption>
							<IonSelectOption value="Janesville">Janesville</IonSelectOption>
							<IonSelectOption value="Jasper">Jasper</IonSelectOption>
							<IonSelectOption value="Jeffers">Jeffers</IonSelectOption>
							<IonSelectOption value="Jenkins">Jenkins</IonSelectOption>
							<IonSelectOption value="Johnson">Johnson</IonSelectOption>
							<IonSelectOption value="Jordan">Jordan</IonSelectOption>
							<IonSelectOption value="Kandiyohi">Kandiyohi</IonSelectOption>
							<IonSelectOption value="Karlstad">Karlstad</IonSelectOption>
							<IonSelectOption value="Kasota">Kasota</IonSelectOption>
							<IonSelectOption value="Kasson">Kasson</IonSelectOption>
							<IonSelectOption value="Keewatin">Keewatin</IonSelectOption>
							<IonSelectOption value="Kelliher">Kelliher</IonSelectOption>
							<IonSelectOption value="Kellogg">Kellogg</IonSelectOption>
							<IonSelectOption value="Kennedy">Kennedy</IonSelectOption>
							<IonSelectOption value="Kenneth">Kenneth</IonSelectOption>
							<IonSelectOption value="Kensington">Kensington</IonSelectOption>
							<IonSelectOption value="Kent">Kent</IonSelectOption>
							<IonSelectOption value="Kenyon">Kenyon</IonSelectOption>
							<IonSelectOption value="Kerkhoven">Kerkhoven</IonSelectOption>
							<IonSelectOption value="Kerrick">Kerrick</IonSelectOption>
							<IonSelectOption value="Kettle River">Kettle River</IonSelectOption>
							<IonSelectOption value="Kiester">Kiester</IonSelectOption>
							<IonSelectOption value="Kilkenny">Kilkenny</IonSelectOption>
							<IonSelectOption value="Kimball">Kimball</IonSelectOption>
							<IonSelectOption value="Kinbrae">Kinbrae</IonSelectOption>
							<IonSelectOption value="Kingston">Kingston</IonSelectOption>
							<IonSelectOption value="Kinney">Kinney</IonSelectOption>
							<IonSelectOption value="La Crescent">La Crescent</IonSelectOption>
							<IonSelectOption value="Lafayette">Lafayette</IonSelectOption>
							<IonSelectOption value="Lake Benton">Lake Benton</IonSelectOption>
							<IonSelectOption value="Lake Bronson">Lake Bronson</IonSelectOption>
							<IonSelectOption value="Lake City">Lake City</IonSelectOption>
							<IonSelectOption value="Lake Crystal">Lake Crystal</IonSelectOption>
							<IonSelectOption value="Lake Elmo">Lake Elmo</IonSelectOption>
							<IonSelectOption value="Lakefield">Lakefield</IonSelectOption>
							<IonSelectOption value="Lake Henry">Lake Henry</IonSelectOption>
							<IonSelectOption value="Lake Lillian">Lake Lillian</IonSelectOption>
							<IonSelectOption value="Lake Park">Lake Park</IonSelectOption>
							<IonSelectOption value="Lake St. Croix Beach">Lake St. Croix Beach</IonSelectOption>
							<IonSelectOption value="Lake Shore">Lake Shore</IonSelectOption>
							<IonSelectOption value="Lake Wilson">Lake Wilson</IonSelectOption>
							<IonSelectOption value="Lakeland">Lakeland</IonSelectOption>
							<IonSelectOption value="Lakeland Shores">Lakeland Shores</IonSelectOption>
							<IonSelectOption value="Lakeville">Lakeville</IonSelectOption>
							<IonSelectOption value="Lamberton">Lamberton</IonSelectOption>
							<IonSelectOption value="Lancaster">Lancaster</IonSelectOption>
							<IonSelectOption value="Landfall">Landfall</IonSelectOption>
							<IonSelectOption value="Lanesboro">Lanesboro</IonSelectOption>
							<IonSelectOption value="La Prairie">La Prairie</IonSelectOption>
							<IonSelectOption value="La Salle">La Salle</IonSelectOption>
							<IonSelectOption value="Laporte">Laporte</IonSelectOption>
							<IonSelectOption value="Lastrup">Lastrup</IonSelectOption>
							<IonSelectOption value="Lauderdale">Lauderdale</IonSelectOption>
							<IonSelectOption value="Le Center">Le Center</IonSelectOption>
							<IonSelectOption value="Le Roy">Le Roy</IonSelectOption>
							<IonSelectOption value="Le Sueur">Le Sueur</IonSelectOption>
							<IonSelectOption value="Lengby">Lengby</IonSelectOption>
							<IonSelectOption value="Leonard">Leonard</IonSelectOption>
							<IonSelectOption value="Leonidas">Leonidas</IonSelectOption>
							<IonSelectOption value="Lester Prairie">Lester Prairie</IonSelectOption>
							<IonSelectOption value="Lewiston">Lewiston</IonSelectOption>
							<IonSelectOption value="Lewisville">Lewisville</IonSelectOption>
							<IonSelectOption value="Lexington">Lexington</IonSelectOption>
							<IonSelectOption value="Lilydale">Lilydale</IonSelectOption>
							<IonSelectOption value="Lindstrom">Lindstrom</IonSelectOption>
							<IonSelectOption value="Lino Lakes">Lino Lakes</IonSelectOption>
							<IonSelectOption value="Lismore">Lismore</IonSelectOption>
							<IonSelectOption value="Litchfield">Litchfield</IonSelectOption>
							<IonSelectOption value="Little Canada">Little Canada</IonSelectOption>
							<IonSelectOption value="Little Falls">Little Falls</IonSelectOption>
							<IonSelectOption value="Littlefork">Littlefork</IonSelectOption>
							<IonSelectOption value="Long Beach">Long Beach</IonSelectOption>
							<IonSelectOption value="Long Lake">Long Lake</IonSelectOption>
							<IonSelectOption value="Long Prairie">Long Prairie</IonSelectOption>
							<IonSelectOption value="Longville">Longville</IonSelectOption>
							<IonSelectOption value="Lonsdale">Lonsdale</IonSelectOption>
							<IonSelectOption value="Loretto">Loretto</IonSelectOption>
							<IonSelectOption value="Louisburg">Louisburg</IonSelectOption>
							<IonSelectOption value="Lowry">Lowry</IonSelectOption>
							<IonSelectOption value="Lucan">Lucan</IonSelectOption>
							<IonSelectOption value="Luverne">Luverne</IonSelectOption>
							<IonSelectOption value="Lyle">Lyle</IonSelectOption>
							<IonSelectOption value="Lynd">Lynd</IonSelectOption>
							<IonSelectOption value="Mabel">Mabel</IonSelectOption>
							<IonSelectOption value="McGrath">McGrath</IonSelectOption>
							<IonSelectOption value="McGregor">McGregor</IonSelectOption>
							<IonSelectOption value="McIntosh">McIntosh</IonSelectOption>
							<IonSelectOption value="McKinley">McKinley</IonSelectOption>
							<IonSelectOption value="Madelia">Madelia</IonSelectOption>
							<IonSelectOption value="Madison">Madison</IonSelectOption>
							<IonSelectOption value="Madison Lake">Madison Lake</IonSelectOption>
							<IonSelectOption value="Magnolia">Magnolia</IonSelectOption>
							<IonSelectOption value="Mahnomen">Mahnomen</IonSelectOption>
							<IonSelectOption value="Mahtomedi">Mahtomedi</IonSelectOption>
							<IonSelectOption value="Manchester">Manchester</IonSelectOption>
							<IonSelectOption value="Manhattan Beach">Manhattan Beach</IonSelectOption>
							<IonSelectOption value="Mankato">Mankato</IonSelectOption>
							<IonSelectOption value="Mantorville">Mantorville</IonSelectOption>
							<IonSelectOption value="Maple Grove">Maple Grove</IonSelectOption>
							<IonSelectOption value="Maple Lake">Maple Lake</IonSelectOption>
							<IonSelectOption value="Maple Plain">Maple Plain</IonSelectOption>
							<IonSelectOption value="Mapleton">Mapleton</IonSelectOption>
							<IonSelectOption value="Mapleview">Mapleview</IonSelectOption>
							<IonSelectOption value="Maplewood">Maplewood</IonSelectOption>
							<IonSelectOption value="Marble">Marble</IonSelectOption>
							<IonSelectOption value="Marietta">Marietta</IonSelectOption>
							<IonSelectOption value="Marine on St. Croix">Marine on St. Croix</IonSelectOption>
							<IonSelectOption value="Marshall">Marshall</IonSelectOption>
							<IonSelectOption value="Mayer">Mayer</IonSelectOption>
							<IonSelectOption value="Maynard">Maynard</IonSelectOption>
							<IonSelectOption value="Mazeppa">Mazeppa</IonSelectOption>
							<IonSelectOption value="Meadowlands">Meadowlands</IonSelectOption>
							<IonSelectOption value="Medford">Medford</IonSelectOption>
							<IonSelectOption value="Medicine Lake">Medicine Lake</IonSelectOption>
							<IonSelectOption value="Medina">Medina</IonSelectOption>
							<IonSelectOption value="Meire Grove">Meire Grove</IonSelectOption>
							<IonSelectOption value="Melrose">Melrose</IonSelectOption>
							<IonSelectOption value="Menahga">Menahga</IonSelectOption>
							<IonSelectOption value="Mendota">Mendota</IonSelectOption>
							<IonSelectOption value="Mendota Heights">Mendota Heights</IonSelectOption>
							<IonSelectOption value="Mentor">Mentor</IonSelectOption>
							<IonSelectOption value="Merriam">Merriam</IonSelectOption>
							<IonSelectOption value="Merrifield">Merrifield</IonSelectOption>
							<IonSelectOption value="Middle River">Middle River</IonSelectOption>
							<IonSelectOption value="Miesville">Miesville</IonSelectOption>
							<IonSelectOption value="Milaca">Milaca</IonSelectOption>
							<IonSelectOption value="Milan">Milan</IonSelectOption>
							<IonSelectOption value="Millerville">Millerville</IonSelectOption>
							<IonSelectOption value="Millville">Millville</IonSelectOption>
							<IonSelectOption value="Milroy">Milroy</IonSelectOption>
							<IonSelectOption value="Miltona">Miltona</IonSelectOption>
							<IonSelectOption value="Minneapolis">Minneapolis</IonSelectOption>
							<IonSelectOption value="Minneiska">Minneiska</IonSelectOption>
							<IonSelectOption value="Minneota">Minneota</IonSelectOption>
							<IonSelectOption value="Minnesota City">Minnesota City</IonSelectOption>
							<IonSelectOption value="Minnesota Lake">Minnesota Lake</IonSelectOption>
							<IonSelectOption value="Minnetonka">Minnetonka</IonSelectOption>
							<IonSelectOption value="Minnetonka Beach">Minnetonka Beach</IonSelectOption>
							<IonSelectOption value="Minnetrista">Minnetrista</IonSelectOption>
							<IonSelectOption value="Mizpah">Mizpah</IonSelectOption>
							<IonSelectOption value="Montevideo">Montevideo</IonSelectOption>
							<IonSelectOption value="Montgomery">Montgomery</IonSelectOption>
							<IonSelectOption value="Monticello">Monticello</IonSelectOption>
							<IonSelectOption value="Montrose">Montrose</IonSelectOption>
							<IonSelectOption value="Moorhead">Moorhead</IonSelectOption>
							<IonSelectOption value="Moose Lake">Moose Lake</IonSelectOption>
							<IonSelectOption value="Mora">Mora</IonSelectOption>
							<IonSelectOption value="Morgan">Morgan</IonSelectOption>
							<IonSelectOption value="Morris">Morris</IonSelectOption>
							<IonSelectOption value="Morristown">Morristown</IonSelectOption>
							<IonSelectOption value="Morton">Morton</IonSelectOption>
							<IonSelectOption value="Motley">Motley</IonSelectOption>
							<IonSelectOption value="Mound">Mound</IonSelectOption>
							<IonSelectOption value="Mounds View">Mounds View</IonSelectOption>
							<IonSelectOption value="Mountain Iron">Mountain Iron</IonSelectOption>
							<IonSelectOption value="Mountain Lake">Mountain Lake</IonSelectOption>
							<IonSelectOption value="Murdock">Murdock</IonSelectOption>
							<IonSelectOption value="Myrtle">Myrtle</IonSelectOption>
							<IonSelectOption value="Nashua">Nashua</IonSelectOption>
							<IonSelectOption value="Nashwauk">Nashwauk</IonSelectOption>
							<IonSelectOption value="Nassau">Nassau</IonSelectOption>
							<IonSelectOption value="Nelson">Nelson</IonSelectOption>
							<IonSelectOption value="Nerstrand">Nerstrand</IonSelectOption>
							<IonSelectOption value="Nevis">Nevis</IonSelectOption>
							<IonSelectOption value="New Auburn">New Auburn</IonSelectOption>
							<IonSelectOption value="New Brighton">New Brighton</IonSelectOption>
							<IonSelectOption value="New Germany">New Germany</IonSelectOption>
							<IonSelectOption value="New Hope">New Hope</IonSelectOption>
							<IonSelectOption value="New London">New London</IonSelectOption>
							<IonSelectOption value="New Market">New Market</IonSelectOption>
							<IonSelectOption value="New Munich">New Munich</IonSelectOption>
							<IonSelectOption value="New Prague">New Prague</IonSelectOption>
							<IonSelectOption value="New Richland">New Richland</IonSelectOption>
							<IonSelectOption value="New Trier">New Trier</IonSelectOption>
							<IonSelectOption value="New Ulm">New Ulm</IonSelectOption>
							<IonSelectOption value="New York Mills">New York Mills</IonSelectOption>
							<IonSelectOption value="Newfolden">Newfolden</IonSelectOption>
							<IonSelectOption value="Newport">Newport</IonSelectOption>
							<IonSelectOption value="Nickerson">Nickerson</IonSelectOption>
							<IonSelectOption value="Nicollet">Nicollet</IonSelectOption>
							<IonSelectOption value="Nielsville">Nielsville</IonSelectOption>
							<IonSelectOption value="Nimrod">Nimrod</IonSelectOption>
							<IonSelectOption value="Nisswa">Nisswa</IonSelectOption>
							<IonSelectOption value="Norcross">Norcross</IonSelectOption>
							<IonSelectOption value="North Branch">North Branch</IonSelectOption>
							<IonSelectOption value="North Mankato">North Mankato</IonSelectOption>
							<IonSelectOption value="North Oaks">North Oaks</IonSelectOption>
							<IonSelectOption value="North St. Paul">North St. Paul</IonSelectOption>
							<IonSelectOption value="Northfield">Northfield</IonSelectOption>
							<IonSelectOption value="Northome">Northome</IonSelectOption>
							<IonSelectOption value="Northrop">Northrop</IonSelectOption>
							<IonSelectOption value="Norwood Young America">Norwood Young America</IonSelectOption>
							<IonSelectOption value="Nowthen">Nowthen</IonSelectOption>
							<IonSelectOption value="Oakdale">Oakdale</IonSelectOption>
							<IonSelectOption value="Oak Grove">Oak Grove</IonSelectOption>
							<IonSelectOption value="Oak Park Heights">Oak Park Heights</IonSelectOption>
							<IonSelectOption value="Odessa">Odessa</IonSelectOption>
							<IonSelectOption value="Odin">Odin</IonSelectOption>
							<IonSelectOption value="Ogema">Ogema</IonSelectOption>
							<IonSelectOption value="Ogilvie">Ogilvie</IonSelectOption>
							<IonSelectOption value="Okabena">Okabena</IonSelectOption>
							<IonSelectOption value="Oklee">Oklee</IonSelectOption>
							<IonSelectOption value="Olivia">Olivia</IonSelectOption>
							<IonSelectOption value="Onamia">Onamia</IonSelectOption>
							<IonSelectOption value="Ormsby">Ormsby</IonSelectOption>
							<IonSelectOption value="Orono">Orono</IonSelectOption>
							<IonSelectOption value="Oronoco">Oronoco</IonSelectOption>
							<IonSelectOption value="Orr">Orr</IonSelectOption>
							<IonSelectOption value="Ortonville">Ortonville</IonSelectOption>
							<IonSelectOption value="Osakis">Osakis</IonSelectOption>
							<IonSelectOption value="Oslo">Oslo</IonSelectOption>
							<IonSelectOption value="Osseo">Osseo</IonSelectOption>
							<IonSelectOption value="Ostrander">Ostrander</IonSelectOption>
							<IonSelectOption value="Otsego">Otsego</IonSelectOption>
							<IonSelectOption value="Ottertail">Ottertail</IonSelectOption>
							<IonSelectOption value="Owatonna">Owatonna</IonSelectOption>
							<IonSelectOption value="Palisade">Palisade</IonSelectOption>
							<IonSelectOption value="Park Rapids">Park Rapids</IonSelectOption>
							<IonSelectOption value="Parkers Prairie">Parkers Prairie</IonSelectOption>
							<IonSelectOption value="Paynesville">Paynesville</IonSelectOption>
							<IonSelectOption value="Pease">Pease</IonSelectOption>
							<IonSelectOption value="Pelican Rapids">Pelican Rapids</IonSelectOption>
							<IonSelectOption value="Pemberton">Pemberton</IonSelectOption>
							<IonSelectOption value="Pennock">Pennock</IonSelectOption>
							<IonSelectOption value="Pequot Lakes">Pequot Lakes</IonSelectOption>
							<IonSelectOption value="Perham">Perham</IonSelectOption>
							<IonSelectOption value="Perley">Perley</IonSelectOption>
							<IonSelectOption value="Peterson">Peterson</IonSelectOption>
							<IonSelectOption value="Pierz">Pierz</IonSelectOption>
							<IonSelectOption value="Pillager">Pillager</IonSelectOption>
							<IonSelectOption value="Pine City">Pine City</IonSelectOption>
							<IonSelectOption value="Pine Island">Pine Island</IonSelectOption>
							<IonSelectOption value="Pine River">Pine River</IonSelectOption>
							<IonSelectOption value="Pine Springs">Pine Springs</IonSelectOption>
							<IonSelectOption value="Pipestone">Pipestone</IonSelectOption>
							<IonSelectOption value="Plainview">Plainview</IonSelectOption>
							<IonSelectOption value="Plato">Plato</IonSelectOption>
							<IonSelectOption value="Pleasant Lake">Pleasant Lake</IonSelectOption>
							<IonSelectOption value="Plummer">Plummer</IonSelectOption>
							<IonSelectOption value="Plymouth">Plymouth</IonSelectOption>
							<IonSelectOption value="Porter">Porter</IonSelectOption>
							<IonSelectOption value="Pratt">Pratt</IonSelectOption>
							<IonSelectOption value="Preston">Preston</IonSelectOption>
							<IonSelectOption value="Princeton">Princeton</IonSelectOption>
							<IonSelectOption value="Prinsburg">Prinsburg</IonSelectOption>
							<IonSelectOption value="Prior Lake">Prior Lake</IonSelectOption>
							<IonSelectOption value="Proctor">Proctor</IonSelectOption>
							<IonSelectOption value="Puposky">Puposky</IonSelectOption>
							<IonSelectOption value="Quamba">Quamba</IonSelectOption>
							<IonSelectOption value="Rochester">Rochester</IonSelectOption>
							<IonSelectOption value="Racine">Racine</IonSelectOption>
							<IonSelectOption value="Ramsey">Ramsey</IonSelectOption>
							<IonSelectOption value="Randall">Randall</IonSelectOption>
							<IonSelectOption value="Randolph">Randolph</IonSelectOption>
							<IonSelectOption value="Ranier">Ranier</IonSelectOption>
							<IonSelectOption value="Raymond">Raymond</IonSelectOption>
							<IonSelectOption value="Red Lake Falls">Red Lake Falls</IonSelectOption>
							<IonSelectOption value="Red Wing">Red Wing</IonSelectOption>
							<IonSelectOption value="Redwood Falls">Redwood Falls</IonSelectOption>
							<IonSelectOption value="Regal">Regal</IonSelectOption>
							<IonSelectOption value="Remer">Remer</IonSelectOption>
							<IonSelectOption value="Renville">Renville</IonSelectOption>
							<IonSelectOption value="Revere">Revere</IonSelectOption>
							<IonSelectOption value="Rice">Rice</IonSelectOption>
							<IonSelectOption value="Richfield">Richfield</IonSelectOption>
							<IonSelectOption value="Richmond">Richmond</IonSelectOption>
							<IonSelectOption value="Richville">Richville</IonSelectOption>
							<IonSelectOption value="Riverton">Riverton</IonSelectOption>
							<IonSelectOption value="Robbinsdale">Robbinsdale</IonSelectOption>
							<IonSelectOption value="Rochester">Rochester</IonSelectOption>
							<IonSelectOption value="Rock Creek">Rock Creek</IonSelectOption>
							<IonSelectOption value="Rockford">Rockford</IonSelectOption>
							<IonSelectOption value="Rockville">Rockville</IonSelectOption>
							<IonSelectOption value="Rogers">Rogers</IonSelectOption>
							<IonSelectOption value="Rollingstone">Rollingstone</IonSelectOption>
							<IonSelectOption value="Ronneby">Ronneby</IonSelectOption>
							<IonSelectOption value="Roosevelt">Roosevelt</IonSelectOption>
							<IonSelectOption value="Roscoe">Roscoe</IonSelectOption>
							<IonSelectOption value="Rose Creek">Rose Creek</IonSelectOption>
							<IonSelectOption value="Roseau">Roseau</IonSelectOption>
							<IonSelectOption value="Rosemount">Rosemount</IonSelectOption>
							<IonSelectOption value="Roseville">Roseville</IonSelectOption>
							<IonSelectOption value="Rothsay">Rothsay</IonSelectOption>
							<IonSelectOption value="Round Lake">Round Lake</IonSelectOption>
							<IonSelectOption value="Royalton">Royalton</IonSelectOption>
							<IonSelectOption value="Rush City">Rush City</IonSelectOption>
							<IonSelectOption value="Rushford">Rushford</IonSelectOption>
							<IonSelectOption value="Rushford Village">Rushford Village</IonSelectOption>
							<IonSelectOption value="Rushmore">Rushmore</IonSelectOption>
							<IonSelectOption value="Russell">Russell</IonSelectOption>
							<IonSelectOption value="Ruthton">Ruthton</IonSelectOption>
							<IonSelectOption value="Rutledge">Rutledge</IonSelectOption>
							<IonSelectOption value="St. Paul, capital of Minnesota">St. Paul, capital of Minnesota</IonSelectOption>
							<IonSelectOption value="Sabin">Sabin</IonSelectOption>
							<IonSelectOption value="Sacred Heart">Sacred Heart</IonSelectOption>
							<IonSelectOption value="St. Anthony">St. Anthony</IonSelectOption>
							<IonSelectOption value="St. Anthony Village">St. Anthony Village</IonSelectOption>
							<IonSelectOption value="St. Augusta">St. Augusta</IonSelectOption>
							<IonSelectOption value="St. Bonifacius">St. Bonifacius</IonSelectOption>
							<IonSelectOption value="St. Charles">St. Charles</IonSelectOption>
							<IonSelectOption value="St. Clair">St. Clair</IonSelectOption>
							<IonSelectOption value="St. Cloud">St. Cloud</IonSelectOption>
							<IonSelectOption value="St. Francis">St. Francis</IonSelectOption>
							<IonSelectOption value="St. Hilaire">St. Hilaire</IonSelectOption>
							<IonSelectOption value="St. James">St. James</IonSelectOption>
							<IonSelectOption value="St. Joseph">St. Joseph</IonSelectOption>
							<IonSelectOption value="St. Leo">St. Leo</IonSelectOption>
							<IonSelectOption value="St. Louis Park">St. Louis Park</IonSelectOption>
							<IonSelectOption value="St. Martin">St. Martin</IonSelectOption>
							<IonSelectOption value="St. Marys Point">St. Marys Point</IonSelectOption>
							<IonSelectOption value="St. Michael">St. Michael</IonSelectOption>
							<IonSelectOption value="St. Paul">St. Paul</IonSelectOption>
							<IonSelectOption value="St. Paul Park">St. Paul Park</IonSelectOption>
							<IonSelectOption value="St. Peter">St. Peter</IonSelectOption>
							<IonSelectOption value="St. Rosa">St. Rosa</IonSelectOption>
							<IonSelectOption value="St. Stephen">St. Stephen</IonSelectOption>
							<IonSelectOption value="St. Vincent">St. Vincent</IonSelectOption>
							<IonSelectOption value="Sanborn">Sanborn</IonSelectOption>
							<IonSelectOption value="Sandstone">Sandstone</IonSelectOption>
							<IonSelectOption value="Sargeant">Sargeant</IonSelectOption>
							<IonSelectOption value="Sartell">Sartell</IonSelectOption>
							<IonSelectOption value="Sauk Centre">Sauk Centre</IonSelectOption>
							<IonSelectOption value="Sauk Rapids">Sauk Rapids</IonSelectOption>
							<IonSelectOption value="Savage">Savage</IonSelectOption>
							<IonSelectOption value="Scandia">Scandia</IonSelectOption>
							<IonSelectOption value="Scanlon">Scanlon</IonSelectOption>
							<IonSelectOption value="Seaforth">Seaforth</IonSelectOption>
							<IonSelectOption value="Sebeka">Sebeka</IonSelectOption>
							<IonSelectOption value="Sedan">Sedan</IonSelectOption>
							<IonSelectOption value="Shafer">Shafer</IonSelectOption>
							<IonSelectOption value="Shakopee">Shakopee</IonSelectOption>
							<IonSelectOption value="Shelly">Shelly</IonSelectOption>
							<IonSelectOption value="Sherburn">Sherburn</IonSelectOption>
							<IonSelectOption value="Shevlin">Shevlin</IonSelectOption>
							<IonSelectOption value="Shoreview">Shoreview</IonSelectOption>
							<IonSelectOption value="Shorewood">Shorewood</IonSelectOption>
							<IonSelectOption value="Silver Bay">Silver Bay</IonSelectOption>
							<IonSelectOption value="Silver Lake">Silver Lake</IonSelectOption>
							<IonSelectOption value="Skyline">Skyline</IonSelectOption>
							<IonSelectOption value="Slayton">Slayton</IonSelectOption>
							<IonSelectOption value="Sleepy Eye">Sleepy Eye</IonSelectOption>
							<IonSelectOption value="Sobieski">Sobieski</IonSelectOption>
							<IonSelectOption value="Solway">Solway</IonSelectOption>
							<IonSelectOption value="South Haven">South Haven</IonSelectOption>
							<IonSelectOption value="South St. Paul">South St. Paul</IonSelectOption>
							<IonSelectOption value="Spicer">Spicer</IonSelectOption>
							<IonSelectOption value="Spring Grove">Spring Grove</IonSelectOption>
							<IonSelectOption value="Spring Hill">Spring Hill</IonSelectOption>
							<IonSelectOption value="Spring Lake Park">Spring Lake Park</IonSelectOption>
							<IonSelectOption value="Spring Park">Spring Park</IonSelectOption>
							<IonSelectOption value="Spring Valley">Spring Valley</IonSelectOption>
							<IonSelectOption value="Springfield">Springfield</IonSelectOption>
							<IonSelectOption value="Squaw Lake">Squaw Lake</IonSelectOption>
							<IonSelectOption value="Stacy">Stacy</IonSelectOption>
							<IonSelectOption value="Staples">Staples</IonSelectOption>
							<IonSelectOption value="Starbuck">Starbuck</IonSelectOption>
							<IonSelectOption value="Steen">Steen</IonSelectOption>
							<IonSelectOption value="Stephen">Stephen</IonSelectOption>
							<IonSelectOption value="Stewart">Stewart</IonSelectOption>
							<IonSelectOption value="Stewartville">Stewartville</IonSelectOption>
							<IonSelectOption value="Stillwater">Stillwater</IonSelectOption>
							<IonSelectOption value="Stockton">Stockton</IonSelectOption>
							<IonSelectOption value="Storden">Storden</IonSelectOption>
							<IonSelectOption value="Strandquist">Strandquist</IonSelectOption>
							<IonSelectOption value="Strathcona">Strathcona</IonSelectOption>
							<IonSelectOption value="Sturgeon Lake">Sturgeon Lake</IonSelectOption>
							<IonSelectOption value="Sunburg">Sunburg</IonSelectOption>
							<IonSelectOption value="Sunfish Lake">Sunfish Lake</IonSelectOption>
							<IonSelectOption value="Swanville">Swanville</IonSelectOption>
							<IonSelectOption value="Taconite">Taconite</IonSelectOption>
							<IonSelectOption value="Tamarack">Tamarack</IonSelectOption>
							<IonSelectOption value="Taopi">Taopi</IonSelectOption>
							<IonSelectOption value="Taunton">Taunton</IonSelectOption>
							<IonSelectOption value="Taylors Falls">Taylors Falls</IonSelectOption>
							<IonSelectOption value="Tenney">Tenney</IonSelectOption>
							<IonSelectOption value="Tenstrike">Tenstrike</IonSelectOption>
							<IonSelectOption value="Thief River Falls">Thief River Falls</IonSelectOption>
							<IonSelectOption value="Thomson">Thomson</IonSelectOption>
							<IonSelectOption value="Tintah">Tintah</IonSelectOption>
							<IonSelectOption value="Tonka Bay">Tonka Bay</IonSelectOption>
							<IonSelectOption value="Tower">Tower</IonSelectOption>
							<IonSelectOption value="Tracy">Tracy</IonSelectOption>
							<IonSelectOption value="Trail">Trail</IonSelectOption>
							<IonSelectOption value="Trimont">Trimont</IonSelectOption>
							<IonSelectOption value="Trommald">Trommald</IonSelectOption>
							<IonSelectOption value="Trosky">Trosky</IonSelectOption>
							<IonSelectOption value="Truman">Truman</IonSelectOption>
							<IonSelectOption value="Turtle River">Turtle River</IonSelectOption>
							<IonSelectOption value="Twin Lakes">Twin Lakes</IonSelectOption>
							<IonSelectOption value="Twin Valley">Twin Valley</IonSelectOption>
							<IonSelectOption value="Two Harbors">Two Harbors</IonSelectOption>
							<IonSelectOption value="Tyler">Tyler</IonSelectOption>
							<IonSelectOption value="Ulen">Ulen</IonSelectOption>
							<IonSelectOption value="Underwood">Underwood</IonSelectOption>
							<IonSelectOption value="Upsala">Upsala</IonSelectOption>
							<IonSelectOption value="Urbank">Urbank</IonSelectOption>
							<IonSelectOption value="Utica">Utica</IonSelectOption>
							<IonSelectOption value="Vadnais Heights">Vadnais Heights</IonSelectOption>
							<IonSelectOption value="Vergas">Vergas</IonSelectOption>
							<IonSelectOption value="Vermillion">Vermillion</IonSelectOption>
							<IonSelectOption value="Verndale">Verndale</IonSelectOption>
							<IonSelectOption value="Vernon Center">Vernon Center</IonSelectOption>
							<IonSelectOption value="Vesta">Vesta</IonSelectOption>
							<IonSelectOption value="Victoria">Victoria</IonSelectOption>
							<IonSelectOption value="Viking">Viking</IonSelectOption>
							<IonSelectOption value="Villard">Villard</IonSelectOption>
							<IonSelectOption value="Vining">Vining</IonSelectOption>
							<IonSelectOption value="Virginia">Virginia</IonSelectOption>
							<IonSelectOption value="Wabasha">Wabasha</IonSelectOption>
							<IonSelectOption value="Wabasso">Wabasso</IonSelectOption>
							<IonSelectOption value="Waconia">Waconia</IonSelectOption>
							<IonSelectOption value="Wadena">Wadena</IonSelectOption>
							<IonSelectOption value="Wahkon">Wahkon</IonSelectOption>
							<IonSelectOption value="Waite Park">Waite Park</IonSelectOption>
							<IonSelectOption value="Waldorf">Waldorf</IonSelectOption>
							<IonSelectOption value="Walker">Walker</IonSelectOption>
							<IonSelectOption value="Walnut Grove">Walnut Grove</IonSelectOption>
							<IonSelectOption value="Walters">Walters</IonSelectOption>
							<IonSelectOption value="Waltham">Waltham</IonSelectOption>
							<IonSelectOption value="Wanamingo">Wanamingo</IonSelectOption>
							<IonSelectOption value="Wanda">Wanda</IonSelectOption>
							<IonSelectOption value="Warba">Warba</IonSelectOption>
							<IonSelectOption value="Warren">Warren</IonSelectOption>
							<IonSelectOption value="Warroad">Warroad</IonSelectOption>
							<IonSelectOption value="Waseca">Waseca</IonSelectOption>
							<IonSelectOption value="Watertown">Watertown</IonSelectOption>
							<IonSelectOption value="Waterville">Waterville</IonSelectOption>
							<IonSelectOption value="Watkins">Watkins</IonSelectOption>
							<IonSelectOption value="Watson">Watson</IonSelectOption>
							<IonSelectOption value="Waubun">Waubun</IonSelectOption>
							<IonSelectOption value="Waverly">Waverly</IonSelectOption>
							<IonSelectOption value="Wayzata">Wayzata</IonSelectOption>
							<IonSelectOption value="Welcome">Welcome</IonSelectOption>
							<IonSelectOption value="Wells">Wells</IonSelectOption>
							<IonSelectOption value="Wendell">Wendell</IonSelectOption>
							<IonSelectOption value="West Concord">West Concord</IonSelectOption>
							<IonSelectOption value="West St. Paul">West St. Paul</IonSelectOption>
							<IonSelectOption value="West Union">West Union</IonSelectOption>
							<IonSelectOption value="Westbrook">Westbrook</IonSelectOption>
							<IonSelectOption value="Westport">Westport</IonSelectOption>
							<IonSelectOption value="Whalan">Whalan</IonSelectOption>
							<IonSelectOption value="Wheaton">Wheaton</IonSelectOption>
							<IonSelectOption value="White Bear Lake">White Bear Lake</IonSelectOption>
							<IonSelectOption value="Wilder">Wilder</IonSelectOption>
							<IonSelectOption value="Willernie">Willernie</IonSelectOption>
							<IonSelectOption value="Williams">Williams</IonSelectOption>
							<IonSelectOption value="Willmar">Willmar</IonSelectOption>
							<IonSelectOption value="Willow River">Willow River</IonSelectOption>
							<IonSelectOption value="Wilmont">Wilmont</IonSelectOption>
							<IonSelectOption value="Wilton">Wilton</IonSelectOption>
							<IonSelectOption value="Windom">Windom</IonSelectOption>
							<IonSelectOption value="Winger">Winger</IonSelectOption>
							<IonSelectOption value="Winnebago">Winnebago</IonSelectOption>
							<IonSelectOption value="Winona">Winona</IonSelectOption>
							<IonSelectOption value="Winsted">Winsted</IonSelectOption>
							<IonSelectOption value="Winthrop">Winthrop</IonSelectOption>
							<IonSelectOption value="Winton">Winton</IonSelectOption>
							<IonSelectOption value="Wolf Lake">Wolf Lake</IonSelectOption>
							<IonSelectOption value="Wolverton">Wolverton</IonSelectOption>
							<IonSelectOption value="Wood Lake">Wood Lake</IonSelectOption>
							<IonSelectOption value="Woodbury">Woodbury</IonSelectOption>
							<IonSelectOption value="Woodland">Woodland</IonSelectOption>
							<IonSelectOption value="Woodstock">Woodstock</IonSelectOption>
							<IonSelectOption value="Worthington">Worthington</IonSelectOption>
						</IonList>			
            </IonSelect>
				</IonItem>
			</IonContent>
		</IonPage>
	);
};

export default Tab3Page;
